// packages/cli/assets/lit/aspect-ratio.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-aspect-ratio')
export class AspectRatio extends LitElement {
  @property({ type: Number }) ratio = 1;
  render() {
    const ratio =
      Number.isFinite(this.ratio) && this.ratio > 0 ? this.ratio : 1;
    return html`<div
      part="root"
      data-ratio=${ratio}
      style=${`aspect-ratio:${ratio}`}
    >
      <slot></slot>
    </div>`;
  }
}

// packages/svelte/src/components/aspect-ratio.svelte
<script lang="ts">
  let { ratio = 1, children, ...props }: { ratio?: number; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
  let safeRatio = $derived(Number.isFinite(ratio) && ratio > 0 ? ratio : 1);
</script>
<div {...props} data-ratio={safeRatio} style:aspect-ratio={String(safeRatio)}>{@render children?.()}</div>
