// packages/angular/src/components/aspect-ratio.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'simurgh-aspect-ratio',
  standalone: true,
  template: `<ng-content />`,
  host: {
    '[style.aspect-ratio]': "'' + safeRatio",
    '[attr.data-ratio]': 'safeRatio',
  },
})
export class AspectRatioComponent {
  @Input() ratio = 1;
  get safeRatio() {
    return Number.isFinite(this.ratio) && this.ratio > 0 ? this.ratio : 1;
  }
}

// packages/svelte/src/components/aspect-ratio.svelte
<script lang="ts">
  let { ratio = 1, children, ...props }: { ratio?: number; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
  let safeRatio = $derived(Number.isFinite(ratio) && ratio > 0 ? ratio : 1);
</script>
<div {...props} data-ratio={safeRatio} style:aspect-ratio={String(safeRatio)}>{@render children?.()}</div>
