// packages/react/src/components/aspect-ratio.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export const AspectRatio = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement> & { ratio?: number }
>(function AspectRatio({ ratio = 1, style, ...props }, ref) {
  const safeRatio = Number.isFinite(ratio) && ratio > 0 ? ratio : 1;
  return (
    <div
      ref={ref}
      data-ratio={safeRatio}
      style={{ aspectRatio: String(safeRatio), ...style }}
      {...props}
    />
  );
});

// packages/svelte/src/components/aspect-ratio.svelte
<script lang="ts">
  let { ratio = 1, children, ...props }: { ratio?: number; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
  let safeRatio = $derived(Number.isFinite(ratio) && ratio > 0 ? ratio : 1);
</script>
<div {...props} data-ratio={safeRatio} style:aspect-ratio={String(safeRatio)}>{@render children?.()}</div>
