// packages/angular/src/components/field.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'simurgh-field',
  standalone: true,
  template: `<fieldset data-slot="field" [disabled]="disabled">
    <ng-content />
  </fieldset>`,
})
export class FieldComponent {
  @Input() disabled = false;
}

@Component({
  selector: 'simurgh-field-legend',
  standalone: true,
  template: `<legend data-slot="field-legend"><ng-content /></legend>`,
})
export class FieldLegendComponent {}

@Component({
  selector: 'simurgh-field-description',
  standalone: true,
  template: `<p data-slot="field-description"><ng-content /></p>`,
})
export class FieldDescriptionComponent {}

@Component({
  selector: 'simurgh-field-error',
  standalone: true,
  template: `<p data-slot="field-error" role="alert"><ng-content /></p>`,
})
export class FieldErrorComponent {}

// packages/svelte/src/components/field.svelte
<script lang="ts">
  let { invalid = false, disabled = false, legend, description, error, children, ...rest }: { invalid?: boolean; disabled?: boolean; legend?: import('svelte').Snippet; description?: import('svelte').Snippet; error?: import('svelte').Snippet; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<fieldset {...rest} {disabled} data-slot="field" data-invalid={invalid || undefined}>
  {#if legend}<legend data-slot="field-legend">{@render legend()}</legend>{/if}
  {@render children?.()}
  {#if description}<div data-slot="field-description">{@render description()}</div>{/if}
  {#if error}<div role="alert" data-slot="field-error">{@render error()}</div>{/if}
</fieldset>
