// packages/lit/src/components/form.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-form')
export class Form extends LitElement {
  @property({ type: Boolean, attribute: 'focus-invalid' }) focusInvalid = true;
  private invalid(event: Event) {
    if (this.focusInvalid)
      queueMicrotask(() => (event.target as HTMLElement).focus());
  }
  render() {
    return html`<form part="form" data-slot="form" @invalid=${this.invalid}>
        <slot></slot>
      </form>
      <div
        part="errors"
        role="alert"
        aria-live="assertive"
        tabindex="-1"
        data-slot="form-error-summary"
      >
        <slot name="errors"></slot>
      </div>`;
  }
}

// packages/svelte/src/components/form.svelte
<script lang="ts">
  let { focusInvalid = true, errors, children, ...rest }: { focusInvalid?: boolean; errors?: import('svelte').Snippet; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
  function invalid(event: Event) { if (focusInvalid) queueMicrotask(() => (event.target as HTMLElement).focus()); }
</script>
<form {...rest} data-slot="form" oninvalid={invalid}>
  {@render children?.()}
  {#if errors}<div role="alert" aria-live="assertive" tabindex="-1" data-slot="form-error-summary">{@render errors()}</div>{/if}
</form>
