// packages/cli/assets/lit/item.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
@customElement('simurgh-item')
export class Item extends LitElement {
  render() {
    return html`<div part="item" data-slot="item">
      <div part="media" data-slot="item-media"><slot name="media"></slot></div>
      <div part="content" data-slot="item-content">
        <div part="title" data-slot="item-title">
          <slot name="title"></slot>
        </div>
        <p part="description" data-slot="item-description">
          <slot name="description"></slot>
        </p>
        <slot></slot>
      </div>
      <div part="actions" data-slot="item-actions">
        <slot name="actions"></slot>
      </div>
    </div>`;
  }
}

// packages/svelte/src/components/item.svelte
<script lang="ts">
  let { media, title, description, actions, children, ...rest }: { media?: import('svelte').Snippet; title?: import('svelte').Snippet; description?: import('svelte').Snippet; actions?: import('svelte').Snippet; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<div {...rest} data-slot="item">{#if media}<div data-slot="item-media">{@render media()}</div>{/if}<div data-slot="item-content">{#if title}<div data-slot="item-title">{@render title()}</div>{/if}{#if description}<p data-slot="item-description">{@render description()}</p>{/if}{@render children?.()}</div>{#if actions}<div data-slot="item-actions">{@render actions()}</div>{/if}</div>
