// packages/lit/src/components/scroll-area.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-scroll-area')
export class ScrollArea extends LitElement {
  @property() orientation: 'vertical' | 'horizontal' | 'both' = 'vertical';
  render() {
    return html`<div
      part="root"
      data-slot="scroll-area"
      data-orientation=${this.orientation}
      tabindex="0"
    >
      <div part="viewport" data-slot="scroll-area-viewport"><slot></slot></div>
    </div>`;
  }
}

// packages/svelte/src/components/scroll-area.svelte
<script lang="ts">let { orientation = 'vertical', children, ...rest }: { orientation?: 'vertical' | 'horizontal' | 'both'; children?: import('svelte').Snippet; [key: string]: unknown } = $props();</script>
<div {...rest} data-slot="scroll-area" data-orientation={orientation}><div data-slot="scroll-area-viewport">{@render children?.()}</div></div>
