// packages/cli/assets/lit/toggle.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-toggle')
export class Toggle extends LitElement {
  @property({ type: Boolean, reflect: true }) pressed = false;
  @property({ type: Boolean, reflect: true }) disabled = false;
  render() {
    return html`<button
      part="button"
      type="button"
      aria-pressed=${this.pressed}
      ?disabled=${this.disabled}
      data-slot="toggle"
      data-state=${this.pressed ? 'on' : 'off'}
      @click=${() => {
        if (!this.disabled) this.pressed = !this.pressed;
      }}
    >
      <slot></slot>
    </button>`;
  }
}

// packages/svelte/src/components/toggle.svelte
<script lang="ts">
  let { pressed = $bindable(false), disabled = false, children, ...rest }: { pressed?: boolean; disabled?: boolean; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<button {...rest} type="button" aria-pressed={pressed} data-slot="toggle" data-state={pressed ? 'on' : 'off'} {disabled} onclick={() => { if (!disabled) pressed = !pressed; }}>{@render children?.()}</button>
