// packages/angular/src/components/avatar.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'simurgh-avatar',
  standalone: true,
  imports: [CommonModule],
  template: `<img
      *ngIf="src"
      [src]="src"
      [alt]="alt"
      [hidden]="!loaded"
      (load)="loaded = true"
      (error)="loaded = false"
    /><span *ngIf="!loaded" data-part="fallback">{{ fallback }}</span>`,
  host: { '[attr.data-state]': "loaded ? 'loaded' : 'fallback'" },
})
export class AvatarComponent {
  private source: string | undefined;
  @Input() set src(value: string | undefined) {
    this.source = value;
    this.loaded = false;
  }
  get src() {
    return this.source;
  }
  @Input({ required: true }) alt = '';
  @Input({ required: true }) fallback = '';
  loaded = false;
}

// packages/cli/assets/lit/avatar.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-avatar')
export class Avatar extends LitElement {
  @property() src = '';
  @property() alt = '';
  @property({ type: Boolean, state: true }) private loaded = false;
  updated(changed: Map<string, unknown>) {
    if (changed.has('src')) this.loaded = false;
  }
  render() {
    return html`<span
      part="root"
      data-state=${this.loaded ? 'loaded' : 'fallback'}
    >
      ${
      this.src
        ? html`<img
            part="image"
            src=${this.src}
            alt=${this.alt}
            ?hidden=${!this.loaded}
            @load=${() => (this.loaded = true)}
            @error=${() => (this.loaded = false)}
          />`
        : null
    }
      ${!this.loaded ? html`<span part="fallback" data-part="fallback"><slot name="fallback"></slot></span>` : null}</span
    >`;
  }
}
