// packages/react/src/components/badge.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export type BadgeTone = 'neutral' | 'accent' | 'success' | 'warning' | 'danger';
export const Badge = /* @__PURE__ */ forwardRef<
  HTMLSpanElement,
  HTMLAttributes<HTMLSpanElement> & { tone?: BadgeTone; status?: boolean }
>(function Badge({ tone = 'neutral', status = false, ...props }, ref) {
  return (
    <span
      ref={ref}
      data-tone={tone}
      role={status ? 'status' : undefined}
      aria-live={status ? 'polite' : undefined}
      {...props}
    />
  );
});

// packages/cli/assets/lit/badge.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
export type BadgeTone = 'neutral' | 'accent' | 'success' | 'warning' | 'danger';
@customElement('simurgh-badge')
export class Badge extends LitElement {
  @property() tone: BadgeTone = 'neutral';
  @property({ type: Boolean }) status = false;
  render() {
    return html`<span
      part="badge"
      data-slot="badge"
      data-tone=${this.tone}
      role=${this.status ? 'status' : 'presentation'}
      aria-live=${this.status ? 'polite' : 'off'}
      ><slot></slot
    ></span>`;
  }
}
