// packages/react/src/components/button-group.tsx
import type { Orientation } from '@simurgh-ui/core';
import { forwardRef, type HTMLAttributes } from 'react';

export const ButtonGroup = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement> & { orientation?: Orientation }
>(function ButtonGroup(
  { orientation = 'horizontal', role = 'group', ...props },
  ref,
) {
  return (
    <div
      ref={ref}
      role={role}
      aria-orientation={orientation}
      data-slot="button-group"
      {...props}
    />
  );
});

export const ButtonGroupText = /* @__PURE__ */ forwardRef<
  HTMLSpanElement,
  HTMLAttributes<HTMLSpanElement>
>(function ButtonGroupText(props, ref) {
  return <span ref={ref} data-slot="button-group-text" {...props} />;
});

export const ButtonGroupSeparator = /* @__PURE__ */ forwardRef<
  HTMLSpanElement,
  HTMLAttributes<HTMLSpanElement> & { orientation?: Orientation }
>(function ButtonGroupSeparator(
  { orientation = 'vertical', role = 'separator', ...props },
  ref,
) {
  return (
    <span
      ref={ref}
      role={role}
      aria-orientation={orientation}
      data-slot="button-group-separator"
      {...props}
    />
  );
});

// packages/cli/assets/lit/button-group.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-button-group')
export class ButtonGroup extends LitElement {
  @property() orientation: 'horizontal' | 'vertical' = 'horizontal';
  render() {
    return html`<div
      part="group"
      role="group"
      data-slot="button-group"
      data-orientation=${this.orientation}
      aria-orientation=${this.orientation}
    >
      <slot></slot>
    </div>`;
  }
}
