// packages/angular/src/components/input.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'simurgh-input',
  standalone: true,
  template: `<input
    data-slot="input"
    [type]="type"
    [name]="name || ''"
    [value]="value"
    [required]="required"
    [disabled]="disabled"
    [attr.aria-invalid]="invalid || null"
    (input)="onInput($event)"
  />`,
})
export class InputComponent {
  @Input() type = 'text';
  @Input() name?: string;
  @Input() value = '';
  @Input() required = false;
  @Input() disabled = false;
  @Input() invalid = false;
  @Output() valueChange = new EventEmitter<string>();
  onInput(event: Event) {
    this.value = (event.target as HTMLInputElement).value;
    this.valueChange.emit(this.value);
  }
}

// packages/cli/assets/lit/input.ts
import { html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { FormControlElement } from '../internal/form-control.js';

@customElement('simurgh-input')
export class Input extends FormControlElement {
  @property() value = '';
  @property() type = 'text';
  @property() placeholder = '';
  @property({ type: Boolean }) invalid = false;
  private initialValue = '';
  connectedCallback() {
    super.connectedCallback();
    this.initialValue = this.value;
    this.updateFormValue(this.value);
  }
  formResetCallback() {
    this.value = this.initialValue;
    this.updateFormValue(this.value);
  }
  private onInput(event: Event) {
    this.value = (event.currentTarget as HTMLInputElement).value;
    this.updateFormValue(this.value);
  }
  render() {
    return html`<input
      part="control"
      data-slot="input"
      .value=${this.value}
      type=${this.type}
      placeholder=${this.placeholder}
      ?disabled=${this.disabled}
      ?required=${this.required}
      aria-invalid=${this.invalid ? 'true' : 'false'}
      @input=${this.onInput}
    />`;
  }
}
