// packages/react/src/components/navigation-menu.tsx
import {
  forwardRef,
  type AnchorHTMLAttributes,
  type HTMLAttributes,
  type LiHTMLAttributes,
} from 'react';

export const NavigationMenu = /* @__PURE__ */ forwardRef<
  HTMLElement,
  HTMLAttributes<HTMLElement> & { label?: string }
>(function NavigationMenu({ label = 'Main navigation', ...props }, ref) {
  return (
    <nav ref={ref} aria-label={label} data-slot="navigation-menu" {...props} />
  );
});

export const NavigationMenuList = /* @__PURE__ */ forwardRef<
  HTMLUListElement,
  HTMLAttributes<HTMLUListElement>
>(function NavigationMenuList(props, ref) {
  return <ul ref={ref} data-slot="navigation-menu-list" {...props} />;
});

export const NavigationMenuItem = /* @__PURE__ */ forwardRef<
  HTMLLIElement,
  LiHTMLAttributes<HTMLLIElement>
>(function NavigationMenuItem(props, ref) {
  return <li ref={ref} data-slot="navigation-menu-item" {...props} />;
});

export const NavigationMenuLink = /* @__PURE__ */ forwardRef<
  HTMLAnchorElement,
  AnchorHTMLAttributes<HTMLAnchorElement> & { current?: boolean }
>(function NavigationMenuLink({ current = false, ...props }, ref) {
  return (
    <a
      ref={ref}
      {...props}
      aria-current={current ? 'page' : props['aria-current']}
      data-slot="navigation-menu-link"
    />
  );
});

// packages/cli/assets/lit/navigation-menu.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
export type NavigationItem = { href: string; label: string; current?: boolean };
@customElement('simurgh-navigation-menu')
export class NavigationMenu extends LitElement {
  @property({ attribute: false }) items: NavigationItem[] = [];
  @property() label = 'Main navigation';
  render() {
    return html`<nav
      part="nav"
      aria-label=${this.label}
      data-slot="navigation-menu"
    >
      <ul>
        ${this.items.map((item) => html`<li><a href=${item.href} aria-current=${item.current ? 'page' : 'false'} data-slot="navigation-menu-link">${item.label}</a></li>`)}
      </ul>
    </nav>`;
  }
}
