// packages/react/src/components/password-input.tsx
import { forwardRef, useState, type InputHTMLAttributes } from 'react';
import { useComponentId } from '../internal/ids.js';

type PasswordInputProps = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type'
> & {
  revealLabel?: string;
  concealLabel?: string;
};
export const PasswordInput = /* @__PURE__ */ forwardRef<
  HTMLInputElement,
  PasswordInputProps
>(function PasswordInput(
  {
    revealLabel = 'Show password',
    concealLabel = 'Hide password',
    disabled,
    ...props
  },
  ref,
) {
  const [revealed, setRevealed] = useState(false);
  const id = useComponentId('password', props.id);
  return (
    <div data-slot="password-input" data-disabled={disabled || undefined}>
      <input
        {...props}
        ref={ref}
        id={id}
        type={revealed ? 'text' : 'password'}
        data-slot="password-input-control"
        disabled={disabled}
      />
      <button
        type="button"
        data-slot="password-input-toggle"
        aria-controls={id}
        aria-label={revealed ? concealLabel : revealLabel}
        aria-pressed={revealed}
        disabled={disabled}
        onClick={() => setRevealed((current) => !current)}
      >
        {revealed ? 'Hide' : 'Show'}
      </button>
    </div>
  );
});

// packages/cli/assets/lit/password-input.ts
import { html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { FormControlElement } from '../internal/form-control.js';
@customElement('simurgh-password-input')
export class PasswordInput extends FormControlElement {
  @property() value = '';
  @property({ type: Boolean }) visible = false;
  @property() label = 'Password';
  protected updated() {
    this.updateFormValue(this.value);
  }
  formResetCallback() {
    this.value = '';
  }
  render() {
    return html`<div part="root" data-slot="password-input">
      <input
        part="input"
        type=${this.visible ? 'text' : 'password'}
        .value=${this.value}
        ?disabled=${this.disabled}
        aria-label=${this.label}
        @input=${(e: Event) => (this.value = (e.target as HTMLInputElement).value)}
      /><button
        type="button"
        aria-label=${this.visible ? 'Hide password' : 'Show password'}
        aria-pressed=${this.visible}
        ?disabled=${this.disabled}
        @click=${() => (this.visible = !this.visible)}
      >
        ${this.visible ? 'Hide' : 'Show'}
      </button>
    </div>`;
  }
}
