// packages/react/src/components/separator.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import type { Orientation } from '@simurgh-ui/core';

export const Separator = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement> & {
    orientation?: Orientation;
    decorative?: boolean;
  }
>(function Separator(
  { orientation = 'horizontal', decorative = false, ...props },
  ref,
) {
  return (
    <div
      ref={ref}
      role={decorative ? 'none' : 'separator'}
      aria-hidden={decorative || undefined}
      aria-orientation={decorative ? undefined : orientation}
      data-orientation={orientation}
      {...props}
    />
  );
});

// packages/cli/assets/lit/separator.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-separator')
export class Separator extends LitElement {
  @property() orientation: 'horizontal' | 'vertical' = 'horizontal';
  render() {
    return html`<div
      role="separator"
      aria-orientation=${this.orientation}
      data-slot="separator"
      data-orientation=${this.orientation}
    ></div>`;
  }
}
