// packages/cli/assets/svelte/tags-input.svelte
<script lang="ts">
  let { value = $bindable<string[]>([]), name, disabled = false, label = 'Tags', ...rest }: { value?: string[]; name?: string; disabled?: boolean; label?: string; [key: string]: unknown } = $props(); let draft = $state('');
  function commit() { const tag = draft.trim(); if (tag && !value.includes(tag)) value = [...value, tag]; draft = ''; }
  function keydown(event: KeyboardEvent) { if (event.key === 'Enter' || event.key === ',') { event.preventDefault(); commit(); } else if (event.key === 'Backspace' && !draft) value = value.slice(0, -1); }
</script>
<div {...rest} data-slot="tags-input">{#each value as tag, index}<span data-slot="tag">{tag}<button type="button" aria-label={`Remove ${tag}`} {disabled} onclick={() => value = value.filter((_, i) => i !== index)}>×</button></span>{/each}<input bind:value={draft} aria-label={label} {disabled} onkeydown={keydown} onblur={commit} />{#if name}<input type="hidden" {name} value={value.join(',')} />{/if}</div>

// packages/cli/assets/lit/tags-input.ts
import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { FormControlElement } from '../internal/form-control.js';
@customElement('simurgh-tags-input')
export class TagsInput extends FormControlElement {
  @property({ attribute: false }) value: string[] = [];
  @property() label = 'Tags';
  @state() private draft = '';
  private commit() {
    const tag = this.draft.trim();
    if (tag && !this.value.includes(tag)) this.value = [...this.value, tag];
    this.draft = '';
  }
  protected updated() {
    this.updateFormValue(this.value.join(','));
  }
  formResetCallback() {
    this.value = [];
    this.draft = '';
  }
  render() {
    return html`<div part="root" data-slot="tags-input">
      ${this.value.map((tag, index) => html`<span part="tag" data-slot="tag">${tag}<button type="button" aria-label=${`Remove ${tag}`} ?disabled=${this.disabled} @click=${() => (this.value = this.value.filter((_, i) => i !== index))}>×</button></span>`)}<input
        .value=${this.draft}
        aria-label=${this.label}
        ?disabled=${this.disabled}
        @input=${(e: Event) => (this.draft = (e.target as HTMLInputElement).value)}
        @blur=${this.commit}
        @keydown=${(e: KeyboardEvent) => {
          if (e.key === 'Enter' || e.key === ',') {
            e.preventDefault();
            this.commit();
          }
        }}
      />
    </div>`;
  }
}
