// packages/svelte/src/components/toolbar.svelte
<script lang="ts">let { label = 'Toolbar', orientation = 'horizontal', children, ...rest }: { label?: string; orientation?: 'horizontal' | 'vertical'; children?: import('svelte').Snippet; [key: string]: unknown } = $props();</script>
<div {...rest} role="toolbar" aria-label={label} aria-orientation={orientation} data-slot="toolbar" data-orientation={orientation}>{@render children?.()}</div>

// packages/cli/assets/lit/toolbar.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-toolbar')
export class Toolbar extends LitElement {
  @property() label = 'Toolbar';
  @property() orientation: 'horizontal' | 'vertical' = 'horizontal';
  render() {
    return html`<div
      part="toolbar"
      role="toolbar"
      aria-label=${this.label}
      aria-orientation=${this.orientation}
      data-slot="toolbar"
      data-orientation=${this.orientation}
    >
      <slot></slot>
    </div>`;
  }
}
