// packages/cli/assets/svelte/collapsible.svelte
<script lang="ts">
  let { open = $bindable(false), disabled = false, trigger, children, ...rest }: { open?: boolean; disabled?: boolean; trigger?: import('svelte').Snippet; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<div {...rest} data-slot="collapsible" data-state={open ? 'open' : 'closed'}>
  <button type="button" data-slot="collapsible-trigger" aria-expanded={open} {disabled} onclick={() => open = !open}>{@render trigger?.()}</button>
  <div data-slot="collapsible-content" hidden={!open}>{@render children?.()}</div>
</div>

// packages/lit/src/components/collapsible.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-collapsible')
export class Collapsible extends LitElement {
  @property({ type: Boolean, reflect: true }) open = false;
  @property({ type: Boolean, reflect: true }) disabled = false;
  render() {
    return html`<div
      part="root"
      data-slot="collapsible"
      data-state=${this.open ? 'open' : 'closed'}
    >
      <button
        part="trigger"
        type="button"
        data-slot="collapsible-trigger"
        aria-expanded=${this.open}
        ?disabled=${this.disabled}
        @click=${() => (this.open = !this.open)}
      >
        <slot name="trigger"></slot>
      </button>
      <div part="content" data-slot="collapsible-content" ?hidden=${!this.open}>
        <slot></slot>
      </div>
    </div>`;
  }
}
