// packages/react/src/components/description-list.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export const DescriptionList = /* @__PURE__ */ forwardRef<
  HTMLDListElement,
  HTMLAttributes<HTMLDListElement>
>(function DescriptionList(props, ref) {
  return <dl ref={ref} data-slot="description-list" {...props} />;
});
export const DescriptionListGroup = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function DescriptionListGroup(props, ref) {
  return <div ref={ref} data-slot="description-list-group" {...props} />;
});
export const DescriptionListTerm = /* @__PURE__ */ forwardRef<
  HTMLElement,
  HTMLAttributes<HTMLElement>
>(function DescriptionListTerm(props, ref) {
  return <dt ref={ref} data-slot="description-list-term" {...props} />;
});
export const DescriptionListDetails = /* @__PURE__ */ forwardRef<
  HTMLElement,
  HTMLAttributes<HTMLElement>
>(function DescriptionListDetails(props, ref) {
  return <dd ref={ref} data-slot="description-list-details" {...props} />;
});

// packages/lit/src/components/description-list.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
export type DescriptionItem = { term: string; details: string };
@customElement('simurgh-description-list')
export class DescriptionList extends LitElement {
  @property({ attribute: false }) items: DescriptionItem[] = [];
  render() {
    return html`<dl part="list" data-slot="description-list">
      ${this.items.map(
        (item) =>
          html`<div part="group" data-slot="description-list-group">
            <dt part="term" data-slot="description-list-term">${item.term}</dt>
            <dd part="details" data-slot="description-list-details">
              ${item.details}
            </dd>
          </div>`,
      )}<slot></slot>
    </dl>`;
  }
}
