// packages/svelte/src/components/empty.svelte
<script lang="ts">
  let { media, title, description, children, ...rest }: { media?: import('svelte').Snippet; title?: import('svelte').Snippet; description?: import('svelte').Snippet; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<div {...rest} data-slot="empty"><div data-slot="empty-header">{#if media}<div data-slot="empty-media">{@render media()}</div>{/if}{#if title}<h3 data-slot="empty-title">{@render title()}</h3>{/if}{#if description}<p data-slot="empty-description">{@render description()}</p>{/if}</div><div data-slot="empty-content">{@render children?.()}</div></div>

// packages/lit/src/components/empty.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
@customElement('simurgh-empty')
export class Empty extends LitElement {
  render() {
    return html`<div part="root" data-slot="empty">
      <div part="header" data-slot="empty-header">
        <div part="media" data-slot="empty-media">
          <slot name="media"></slot>
        </div>
        <h3 part="title" data-slot="empty-title"><slot name="title"></slot></h3>
        <p part="description" data-slot="empty-description">
          <slot name="description"></slot>
        </p>
      </div>
      <div part="content" data-slot="empty-content"><slot></slot></div>
    </div>`;
  }
}
