// packages/svelte/src/components/field.svelte
<script lang="ts">
  let { invalid = false, disabled = false, legend, description, error, children, ...rest }: { invalid?: boolean; disabled?: boolean; legend?: import('svelte').Snippet; description?: import('svelte').Snippet; error?: import('svelte').Snippet; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<fieldset {...rest} {disabled} data-slot="field" data-invalid={invalid || undefined}>
  {#if legend}<legend data-slot="field-legend">{@render legend()}</legend>{/if}
  {@render children?.()}
  {#if description}<div data-slot="field-description">{@render description()}</div>{/if}
  {#if error}<div role="alert" data-slot="field-error">{@render error()}</div>{/if}
</fieldset>

// packages/lit/src/components/field.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-field')
export class Field extends LitElement {
  @property({ type: Boolean, reflect: true }) invalid = false;
  @property({ type: Boolean, reflect: true }) disabled = false;
  render() {
    return html`<fieldset
      part="field"
      ?disabled=${this.disabled}
      data-slot="field"
      ?data-invalid=${this.invalid}
    >
      <legend part="legend" data-slot="field-legend">
        <slot name="legend"></slot>
      </legend>
      <slot></slot>
      <div part="description" data-slot="field-description">
        <slot name="description"></slot>
      </div>
      <div part="error" role="alert" data-slot="field-error">
        <slot name="error"></slot>
      </div>
    </fieldset>`;
  }
}
