// packages/svelte/src/components/meter.svelte
<script lang="ts">
  let { label, min = 0, max = 100, value = 0, children }: { label?: string; min?: number; max?: number; value?: number; children?: import('svelte').Snippet } = $props();
  let safeValue = $derived(Math.min(Number(max), Math.max(Number(min), Number(value))));
</script>
<meter {min} {max} value={safeValue} role="meter" aria-valuenow={safeValue} aria-valuemin={min} aria-valuemax={max} aria-label={label} data-slot="meter">
  {#if children}{@render children()}{:else}{safeValue}{/if}
</meter>

// packages/lit/src/components/meter.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-meter')
export class Meter extends LitElement {
  @property({ type: Number }) min = 0;
  @property({ type: Number }) max = 100;
  @property({ type: Number }) value = 0;
  @property() label = '';
  render() {
    const safe = Math.min(this.max, Math.max(this.min, this.value));
    return html`<meter
      part="meter"
      min=${this.min}
      max=${this.max}
      value=${safe}
      role="meter"
      aria-valuenow=${safe}
      aria-valuemin=${this.min}
      aria-valuemax=${this.max}
      aria-label=${this.label}
      data-slot="meter"
    >
      ${safe}
    </meter>`;
  }
}
