// packages/react/src/components/number-input.tsx
import { forwardRef, useId, useState, type InputHTMLAttributes } from 'react';

type NumberInputProps = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type' | 'value' | 'defaultValue' | 'min' | 'max' | 'step'
> & {
  value?: number;
  defaultValue?: number;
  min?: number;
  max?: number;
  step?: number;
  incrementLabel?: string;
  decrementLabel?: string;
  onValueChange?: (value: number) => void;
};
export const NumberInput = /* @__PURE__ */ forwardRef<
  HTMLInputElement,
  NumberInputProps
>(function NumberInput(
  {
    value,
    defaultValue = 0,
    min,
    max,
    step = 1,
    disabled,
    readOnly,
    incrementLabel = 'Increase value',
    decrementLabel = 'Decrease value',
    onValueChange,
    onChange,
    ...props
  },
  ref,
) {
  const [localValue, setLocalValue] = useState(defaultValue);
  const current = value ?? localValue;
  const safeStep = Number.isFinite(step) && step > 0 ? step : 1;
  const inputId = props.id ?? `simurgh-number-${useId().replace(/:/g, '')}`;
  const normalize = (next: number) =>
    Math.min(max ?? Infinity, Math.max(min ?? -Infinity, next));
  const commit = (next: number) => {
    const normalized = normalize(next);
    if (value === undefined) setLocalValue(normalized);
    onValueChange?.(normalized);
  };
  return (
    <div
      data-slot="number-input"
      data-disabled={disabled || undefined}
      data-readonly={readOnly || undefined}
    >
      <button
        type="button"
        data-slot="number-input-decrement"
        aria-label={decrementLabel}
        aria-controls={inputId}
        disabled={disabled || readOnly || current <= (min ?? -Infinity)}
        onClick={() => commit(current - safeStep)}
      >
        −
      </button>
      <input
        {...props}
        ref={ref}
        id={inputId}
        type="number"
        data-slot="number-input-control"
        value={current}
        min={min}
        max={max}
        step={safeStep}
        disabled={disabled}
        readOnly={readOnly}
        onChange={(event) => {
          onChange?.(event);
          if (!Number.isNaN(event.currentTarget.valueAsNumber))
            commit(event.currentTarget.valueAsNumber);
        }}
      />
      <button
        type="button"
        data-slot="number-input-increment"
        aria-label={incrementLabel}
        aria-controls={inputId}
        disabled={disabled || readOnly || current >= (max ?? Infinity)}
        onClick={() => commit(current + safeStep)}
      >
        +
      </button>
    </div>
  );
});

// packages/lit/src/components/number-input.ts
import { html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { FormControlElement } from '../internal/form-control.js';
@customElement('simurgh-number-input')
export class NumberInput extends FormControlElement {
  @property({ type: Number }) value = 0;
  @property({ type: Number }) min?: number;
  @property({ type: Number }) max?: number;
  @property({ type: Number }) step = 1;
  @property() label = 'Number';
  private set(next: number) {
    this.value = Math.min(
      this.max ?? Infinity,
      Math.max(this.min ?? -Infinity, next),
    );
  }
  protected updated() {
    this.updateFormValue(String(this.value));
  }
  formResetCallback() {
    this.value = 0;
  }
  render() {
    return html`<div part="root" data-slot="number-input">
      <button
        type="button"
        aria-label=${`Decrease ${this.label}`}
        ?disabled=${this.disabled}
        @click=${() => this.set(this.value - this.step)}
      >
        −</button
      ><input
        type="number"
        .value=${String(this.value)}
        min=${this.min ?? ''}
        max=${this.max ?? ''}
        step=${this.step}
        ?disabled=${this.disabled}
        aria-label=${this.label}
        @input=${(e: Event) => this.set((e.target as HTMLInputElement).valueAsNumber)}
      /><button
        type="button"
        aria-label=${`Increase ${this.label}`}
        ?disabled=${this.disabled}
        @click=${() => this.set(this.value + this.step)}
      >
        +
      </button>
    </div>`;
  }
}
