// packages/react/src/components/skeleton.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export const Skeleton = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement> & { label?: string }
>(function Skeleton({ label, ...props }, ref) {
  return (
    <div
      ref={ref}
      role={label ? 'status' : undefined}
      aria-label={label}
      aria-busy={label ? 'true' : undefined}
      aria-hidden={label ? undefined : 'true'}
      data-state="loading"
      {...props}
    />
  );
});

// packages/lit/src/components/skeleton.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-skeleton')
export class Skeleton extends LitElement {
  @property() label = '';
  render() {
    return html`<div
      part="skeleton"
      role=${this.label ? 'status' : 'presentation'}
      aria-label=${this.label}
      aria-busy=${this.label ? 'true' : 'false'}
      aria-hidden=${this.label ? 'false' : 'true'}
      data-state="loading"
    >
      <slot></slot>
    </div>`;
  }
}
