// packages/angular/src/chart-responsive.ts
import { Component, ElementRef, EventEmitter, Output, ViewChild } from '@angular/core';

export type ChartResponsiveSize = { width: number; height: number };

@Component({ selector: 'simurgh-chart-responsive-container', standalone: true, template: '<div #container data-part="responsive-container" style="width:100%;height:100%"><ng-content /></div>' })
export class ChartResponsiveContainerComponent {
  @Output() readonly sizeChange = new EventEmitter<ChartResponsiveSize>();
  @ViewChild('container') set container(value: ElementRef<HTMLElement> | undefined) {
    this.observer?.disconnect();
    if (!value || typeof ResizeObserver === 'undefined') return;
    const update = (width: number, height: number) => this.sizeChange.emit({ width, height });
    const node = value.nativeElement;
    update(node.getBoundingClientRect().width, node.getBoundingClientRect().height);
    this.observer = new ResizeObserver((entries) => { const rect = entries[0]?.contentRect; if (rect) update(rect.width, rect.height); });
    this.observer.observe(node);
  }
  private observer?: ResizeObserver;
  ngOnDestroy() { this.observer?.disconnect(); }
}

// packages/react/src/chart-responsive.tsx
import { useEffect, useRef, useState, type ReactNode } from 'react';

export type ChartResponsiveSize = { width: number; height: number };

export function ChartResponsiveContainer({ aspectRatio = 16 / 9, minWidth = 0, minHeight = 0, children }: {
  aspectRatio?: number;
  minWidth?: number;
  minHeight?: number;
  children: (size: ChartResponsiveSize) => ReactNode;
}) {
  const element = useRef<HTMLDivElement>(null);
  const [size, setSize] = useState<ChartResponsiveSize>({ width: minWidth, height: minHeight });
  useEffect(() => {
    const node = element.current;
    if (!node || typeof ResizeObserver === 'undefined') return;
    const update = (width: number) => setSize({ width: Math.max(minWidth, width), height: Math.max(minHeight, width / aspectRatio) });
    update(node.getBoundingClientRect().width);
    const observer = new ResizeObserver((entries) => update(entries[0]?.contentRect.width ?? 0));
    observer.observe(node);
    return () => observer.disconnect();
  }, [aspectRatio, minHeight, minWidth]);
  return <div ref={element} data-part="responsive-container" style={{ width: '100%', minWidth, minHeight, aspectRatio }}>{size.width > 0 ? children(size) : null}</div>;
}
