// packages/cli/assets/svelte/card.svelte
<script lang="ts">
  let { header, title, description, children, footer, ...rest }: { header?: import('svelte').Snippet; title?: import('svelte').Snippet; description?: import('svelte').Snippet; children?: import('svelte').Snippet; footer?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<div {...rest} data-slot="card">
  {#if header || title || description}<div data-slot="card-header">{@render header?.()}{#if title}<h3 data-slot="card-title">{@render title()}</h3>{/if}{#if description}<p data-slot="card-description">{@render description()}</p>{/if}</div>{/if}
  <div data-slot="card-content">{@render children?.()}</div>
  {#if footer}<div data-slot="card-footer">{@render footer()}</div>{/if}
</div>

// packages/react/src/components/card.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export const Card = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function Card(props, ref) {
  return <div ref={ref} data-slot="card" {...props} />;
});

export const CardHeader = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function CardHeader(props, ref) {
  return <div ref={ref} data-slot="card-header" {...props} />;
});

export const CardTitle = /* @__PURE__ */ forwardRef<
  HTMLHeadingElement,
  HTMLAttributes<HTMLHeadingElement>
>(function CardTitle(props, ref) {
  return <h3 ref={ref} data-slot="card-title" {...props} />;
});

export const CardDescription = /* @__PURE__ */ forwardRef<
  HTMLParagraphElement,
  HTMLAttributes<HTMLParagraphElement>
>(function CardDescription(props, ref) {
  return <p ref={ref} data-slot="card-description" {...props} />;
});

export const CardContent = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function CardContent(props, ref) {
  return <div ref={ref} data-slot="card-content" {...props} />;
});

export const CardFooter = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function CardFooter(props, ref) {
  return <div ref={ref} data-slot="card-footer" {...props} />;
});
