// packages/svelte/src/components/field.svelte
<script lang="ts">
  let { invalid = false, disabled = false, legend, description, error, children, ...rest }: { invalid?: boolean; disabled?: boolean; legend?: import('svelte').Snippet; description?: import('svelte').Snippet; error?: import('svelte').Snippet; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<fieldset {...rest} {disabled} data-slot="field" data-invalid={invalid || undefined}>
  {#if legend}<legend data-slot="field-legend">{@render legend()}</legend>{/if}
  {@render children?.()}
  {#if description}<div data-slot="field-description">{@render description()}</div>{/if}
  {#if error}<div role="alert" data-slot="field-error">{@render error()}</div>{/if}
</fieldset>

// packages/react/src/components/field.tsx
import {
  forwardRef,
  type FieldsetHTMLAttributes,
  type HTMLAttributes,
} from 'react';

export const Field = /* @__PURE__ */ forwardRef<
  HTMLFieldSetElement,
  FieldsetHTMLAttributes<HTMLFieldSetElement>
>(function Field(props, ref) {
  return <fieldset ref={ref} data-slot="field" {...props} />;
});
export const FieldLegend = /* @__PURE__ */ forwardRef<
  HTMLLegendElement,
  HTMLAttributes<HTMLLegendElement>
>(function FieldLegend(props, ref) {
  return <legend ref={ref} data-slot="field-legend" {...props} />;
});
export const FieldDescription = /* @__PURE__ */ forwardRef<
  HTMLParagraphElement,
  HTMLAttributes<HTMLParagraphElement>
>(function FieldDescription(props, ref) {
  return <p ref={ref} data-slot="field-description" {...props} />;
});
export const FieldError = /* @__PURE__ */ forwardRef<
  HTMLParagraphElement,
  HTMLAttributes<HTMLParagraphElement>
>(function FieldError(props, ref) {
  return <p ref={ref} data-slot="field-error" role="alert" {...props} />;
});
