// packages/svelte/src/components/meter.svelte
<script lang="ts">
  let { label, min = 0, max = 100, value = 0, children }: { label?: string; min?: number; max?: number; value?: number; children?: import('svelte').Snippet } = $props();
  let safeValue = $derived(Math.min(Number(max), Math.max(Number(min), Number(value))));
</script>
<meter {min} {max} value={safeValue} role="meter" aria-valuenow={safeValue} aria-valuemin={min} aria-valuemax={max} aria-label={label} data-slot="meter">
  {#if children}{@render children()}{:else}{safeValue}{/if}
</meter>

// packages/react/src/components/meter.tsx
import { forwardRef, type MeterHTMLAttributes } from 'react';

export const Meter = /* @__PURE__ */ forwardRef<
  HTMLMeterElement,
  MeterHTMLAttributes<HTMLMeterElement> & { label?: string }
>(function Meter(
  { label, min = 0, max = 100, value = 0, children, ...props },
  ref,
) {
  const safeValue = Math.min(Number(max), Math.max(Number(min), Number(value)));
  return (
    <meter
      ref={ref}
      min={min}
      max={max}
      value={safeValue}
      role="meter"
      aria-label={label}
      data-slot="meter"
      {...props}
    >
      {children ?? `${safeValue}`}
    </meter>
  );
});
