// packages/angular/src/components/number-input.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { createId } from '@simurgh-ui/core';

@Component({
  selector: 'simurgh-number-input',
  standalone: true,
  template: `<div
    data-slot="number-input"
    [attr.data-disabled]="disabled || null"
    [attr.data-readonly]="readonly || null"
  >
    <button
      type="button"
      data-slot="number-input-decrement"
      [attr.aria-label]="decrementLabel"
      [attr.aria-controls]="inputId"
      [disabled]="disabled || readonly || value <= lowerBound"
      (click)="changeBy(-safeStep)"
    >
      −
    </button>
    <input
      #control
      [id]="inputId"
      type="number"
      data-slot="number-input-control"
      [attr.aria-label]="ariaLabel"
      [attr.name]="name || null"
      [value]="value"
      [min]="min"
      [max]="max"
      [step]="safeStep"
      [disabled]="disabled"
      [readOnly]="readonly"
      [required]="required"
      (input)="setValue(control.valueAsNumber)"
    />
    <button
      type="button"
      data-slot="number-input-increment"
      [attr.aria-label]="incrementLabel"
      [attr.aria-controls]="inputId"
      [disabled]="disabled || readonly || value >= upperBound"
      (click)="changeBy(safeStep)"
    >
      +
    </button>
  </div>`,
})
export class NumberInputComponent {
  @Input() inputId = createId('number');
  @Input('aria-label') ariaLabel = 'Number';
  @Input() value = 0;
  @Input() min: number | undefined;
  @Input() max: number | undefined;
  @Input() step = 1;
  @Input() name?: string;
  @Input() disabled = false;
  @Input() readonly = false;
  @Input() required = false;
  @Input() incrementLabel = 'Increase value';
  @Input() decrementLabel = 'Decrease value';
  @Output() valueChange = new EventEmitter<number>();
  get safeStep() {
    return Number.isFinite(this.step) && this.step > 0 ? this.step : 1;
  }
  get lowerBound() {
    return this.min ?? -Infinity;
  }
  get upperBound() {
    return this.max ?? Infinity;
  }
  changeBy(amount: number) {
    this.setValue(this.value + amount);
  }
  setValue(next: number) {
    if (Number.isNaN(next)) return;
    this.value = Math.min(this.upperBound, Math.max(this.lowerBound, next));
    this.valueChange.emit(this.value);
  }
}

// packages/react/src/components/number-input.tsx
import { forwardRef, useId, useState, type InputHTMLAttributes } from 'react';

type NumberInputProps = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type' | 'value' | 'defaultValue' | 'min' | 'max' | 'step'
> & {
  value?: number;
  defaultValue?: number;
  min?: number;
  max?: number;
  step?: number;
  incrementLabel?: string;
  decrementLabel?: string;
  onValueChange?: (value: number) => void;
};
export const NumberInput = /* @__PURE__ */ forwardRef<
  HTMLInputElement,
  NumberInputProps
>(function NumberInput(
  {
    value,
    defaultValue = 0,
    min,
    max,
    step = 1,
    disabled,
    readOnly,
    incrementLabel = 'Increase value',
    decrementLabel = 'Decrease value',
    onValueChange,
    onChange,
    ...props
  },
  ref,
) {
  const [localValue, setLocalValue] = useState(defaultValue);
  const current = value ?? localValue;
  const safeStep = Number.isFinite(step) && step > 0 ? step : 1;
  const inputId = props.id ?? `simurgh-number-${useId().replace(/:/g, '')}`;
  const normalize = (next: number) =>
    Math.min(max ?? Infinity, Math.max(min ?? -Infinity, next));
  const commit = (next: number) => {
    const normalized = normalize(next);
    if (value === undefined) setLocalValue(normalized);
    onValueChange?.(normalized);
  };
  return (
    <div
      data-slot="number-input"
      data-disabled={disabled || undefined}
      data-readonly={readOnly || undefined}
    >
      <button
        type="button"
        data-slot="number-input-decrement"
        aria-label={decrementLabel}
        aria-controls={inputId}
        disabled={disabled || readOnly || current <= (min ?? -Infinity)}
        onClick={() => commit(current - safeStep)}
      >
        −
      </button>
      <input
        {...props}
        ref={ref}
        id={inputId}
        type="number"
        data-slot="number-input-control"
        value={current}
        min={min}
        max={max}
        step={safeStep}
        disabled={disabled}
        readOnly={readOnly}
        onChange={(event) => {
          onChange?.(event);
          if (!Number.isNaN(event.currentTarget.valueAsNumber))
            commit(event.currentTarget.valueAsNumber);
        }}
      />
      <button
        type="button"
        data-slot="number-input-increment"
        aria-label={incrementLabel}
        aria-controls={inputId}
        disabled={disabled || readOnly || current >= (max ?? Infinity)}
        onClick={() => commit(current + safeStep)}
      >
        +
      </button>
    </div>
  );
});
