// packages/angular/src/components/resizable.ts
import type { Direction, Orientation } from '@simurgh-ui/core';
import type { OnDestroy, OnInit } from '@angular/core';
import {
  Component,
  ElementRef,
  HostBinding,
  HostListener,
  inject,
  Input,
} from '@angular/core';

@Component({
  selector: 'simurgh-resizable-panel-group',
  standalone: true,
  template: `<ng-content />`,
  host: {
    'data-slot': 'resizable-panel-group',
    '[attr.data-orientation]': 'orientation',
    '[attr.dir]': 'direction',
  },
})
export class ResizablePanelGroupComponent {
  @Input() orientation: Orientation = 'horizontal';
  @Input() direction: Direction = 'ltr';
  readonly element = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly panels: ResizablePanelComponent[] = [];
  sizes: number[] = [];
  minimums: number[] = [];
  maximums: number[] = [];
  defaults: number[] = [];

  get count() {
    return this.panels.length;
  }
  register(panel: ResizablePanelComponent) {
    this.panels.push(panel);
    this.defaults.push(1);
    this.minimums.push(10);
    this.maximums.push(90);
    this.normalize();
  }
  configure(
    panel: ResizablePanelComponent,
    defaultSize: number,
    minSize: number,
    maxSize: number,
  ) {
    const index = this.panels.indexOf(panel);
    if (index < 0) return;
    this.defaults[index] = defaultSize;
    this.minimums[index] = minSize;
    this.maximums[index] = maxSize;
    this.normalize();
  }
  unregister(panel: ResizablePanelComponent) {
    const index = this.panels.indexOf(panel);
    if (index < 0) return;
    this.panels.splice(index, 1);
    this.defaults.splice(index, 1);
    this.minimums.splice(index, 1);
    this.maximums.splice(index, 1);
    this.normalize();
  }
  panelIndex(panel: ResizablePanelComponent) {
    return this.panels.indexOf(panel);
  }
  normalize() {
    const total = this.defaults.reduce(
      (sum, value) => sum + Math.max(0, value),
      0,
    );
    this.sizes = this.defaults.map((value) =>
      total ? (Math.max(0, value) / total) * 100 : 100 / this.count,
    );
  }
  adjust(boundary: number, delta: number) {
    if (boundary < 0 || boundary >= this.sizes.length - 1) return;
    const total = this.sizes[boundary]! + this.sizes[boundary + 1]!;
    const low = Math.max(
      this.minimums[boundary]!,
      total - this.maximums[boundary + 1]!,
    );
    const high = Math.min(
      this.maximums[boundary]!,
      total - this.minimums[boundary + 1]!,
    );
    const before = Math.max(low, Math.min(high, this.sizes[boundary]! + delta));
    this.sizes[boundary] = before;
    this.sizes[boundary + 1] = total - before;
  }
}

@Component({
  selector: 'simurgh-resizable-panel',
  standalone: true,
  template: `<ng-content />`,
  host: { 'data-slot': 'resizable-panel' },
})
export class ResizablePanelComponent implements OnInit, OnDestroy {
  @Input() defaultSize = 1;
  @Input() minSize = 10;
  @Input() maxSize = 90;
  private group = inject(ResizablePanelGroupComponent);
  constructor() {
    this.group.register(this);
  }
  @HostBinding('style.flex-basis') get basis() {
    return `${this.group.sizes[this.group.panelIndex(this)] ?? 100}%`;
  }
  ngOnInit() {
    this.group.configure(this, this.defaultSize, this.minSize, this.maxSize);
  }
  ngOnDestroy() {
    this.group.unregister(this);
  }
}

@Component({
  selector: 'simurgh-resizable-handle',
  standalone: true,
  template: `<ng-content />`,
  host: {
    'data-slot': 'resizable-handle',
    role: 'separator',
    tabindex: '0',
  },
})
export class ResizableHandleComponent {
  private group = inject(ResizablePanelGroupComponent);
  readonly boundary = this.group.count - 1;
  @HostBinding('attr.aria-orientation') get ariaOrientation() {
    return this.group.orientation === 'horizontal' ? 'vertical' : 'horizontal';
  }
  @HostBinding('attr.aria-valuemin') get minimum() {
    return Math.max(
      this.group.minimums[this.boundary]!,
      (this.group.sizes[this.boundary] ?? 0) +
        (this.group.sizes[this.boundary + 1] ?? 0) -
        this.group.maximums[this.boundary + 1]!,
    );
  }
  @HostBinding('attr.aria-valuemax') get maximum() {
    return Math.min(
      this.group.maximums[this.boundary]!,
      (this.group.sizes[this.boundary] ?? 0) +
        (this.group.sizes[this.boundary + 1] ?? 0) -
        this.group.minimums[this.boundary + 1]!,
    );
  }
  @HostBinding('attr.aria-valuenow') get value() {
    return Math.round(this.group.sizes[this.boundary] ?? 0);
  }
  @HostListener('keydown', ['$event']) onKeydown(event: KeyboardEvent) {
    const current = this.group.sizes[this.boundary] ?? 0;
    if (event.key === 'Home')
      this.group.adjust(this.boundary, this.minimum - current);
    else if (event.key === 'End')
      this.group.adjust(this.boundary, this.maximum - current);
    else {
      const previous =
        this.group.orientation === 'vertical'
          ? 'ArrowUp'
          : this.group.direction === 'rtl'
            ? 'ArrowRight'
            : 'ArrowLeft';
      const next =
        this.group.orientation === 'vertical'
          ? 'ArrowDown'
          : this.group.direction === 'rtl'
            ? 'ArrowLeft'
            : 'ArrowRight';
      if (event.key === previous) this.group.adjust(this.boundary, -5);
      else if (event.key === next) this.group.adjust(this.boundary, 5);
      else return;
    }
    event.preventDefault();
  }
  @HostListener('pointerdown', ['$event']) onPointerdown(event: PointerEvent) {
    let previous =
      this.group.orientation === 'horizontal' ? event.clientX : event.clientY;
    const root = this.group.element.nativeElement;
    const size =
      this.group.orientation === 'horizontal'
        ? root.clientWidth
        : root.clientHeight;
    if (!size) return;
    const onMove = (next: PointerEvent) => {
      const coordinate =
        this.group.orientation === 'horizontal' ? next.clientX : next.clientY;
      let delta = ((coordinate - previous) / size) * 100;
      previous = coordinate;
      if (
        this.group.orientation === 'horizontal' &&
        this.group.direction === 'rtl'
      )
        delta *= -1;
      this.group.adjust(this.boundary, delta);
    };
    const onUp = () => {
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
    };
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp, { once: true });
  }
}

// packages/react/src/components/resizable.tsx
import { type Direction, type Orientation } from '@simurgh-ui/core';
import React, {
  createContext,
  useContext,
  useRef,
  useState,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
} from 'react';

type ResizableContextValue = {
  orientation: Orientation;
  direction: Direction;
  sizes: number[];
  minimums: number[];
  maximums: number[];
  root: React.RefObject<HTMLDivElement | null>;
  adjust(boundary: number, delta: number): void;
};
const ResizableContext =
  /* @__PURE__ */ createContext<ResizableContextValue | null>(null);
const normalizePanelSizes = (values: number[]) => {
  const total = values.reduce((sum, value) => sum + Math.max(0, value), 0);
  return values.map((value) =>
    total ? (Math.max(0, value) / total) * 100 : 100 / values.length,
  );
};

export function ResizablePanelGroup({
  orientation = 'horizontal',
  direction = 'ltr',
  children,
  ...props
}: HTMLAttributes<HTMLDivElement> & {
  orientation?: Orientation;
  direction?: Direction;
}) {
  const parts = React.Children.toArray(children);
  const panels = parts.filter(
    (child) => React.isValidElement(child) && child.type === ResizablePanel,
  ) as React.ReactElement<ResizablePanelProps>[];
  const [sizes, setSizes] = useState(() =>
    normalizePanelSizes(panels.map((panel) => panel.props.defaultSize ?? 1)),
  );
  const minimums = panels.map((panel) => panel.props.minSize ?? 10);
  const maximums = panels.map((panel) => panel.props.maxSize ?? 90);
  const root = useRef<HTMLDivElement>(null);
  const adjust = (boundary: number, delta: number) => {
    setSizes((current) => {
      if (boundary < 0 || boundary >= current.length - 1) return current;
      const total = current[boundary]! + current[boundary + 1]!;
      const low = Math.max(
        minimums[boundary]!,
        total - maximums[boundary + 1]!,
      );
      const high = Math.min(
        maximums[boundary]!,
        total - minimums[boundary + 1]!,
      );
      const before = Math.max(low, Math.min(high, current[boundary]! + delta));
      const next = [...current];
      next[boundary] = before;
      next[boundary + 1] = total - before;
      return next;
    });
  };
  let panelIndex = 0;
  return (
    <ResizableContext.Provider
      value={{
        orientation,
        direction,
        sizes,
        minimums,
        maximums,
        root,
        adjust,
      }}
    >
      <div
        {...props}
        ref={root}
        data-slot="resizable-panel-group"
        data-orientation={orientation}
        dir={direction}
      >
        {parts.map((child, index) => {
          if (!React.isValidElement(child)) return child;
          if (child.type === ResizablePanel) {
            const current = panelIndex++;
            return React.cloneElement(
              child as React.ReactElement<ResizablePanelProps>,
              { _index: current, key: child.key ?? index },
            );
          }
          if (child.type === ResizableHandle)
            return React.cloneElement(
              child as React.ReactElement<ResizableHandleProps>,
              { _boundary: panelIndex - 1, key: child.key ?? index },
            );
          return child;
        })}
      </div>
    </ResizableContext.Provider>
  );
}

type ResizablePanelProps = HTMLAttributes<HTMLDivElement> & {
  defaultSize?: number;
  minSize?: number;
  maxSize?: number;
  _index?: number;
};
export function ResizablePanel(props: ResizablePanelProps) {
  const context = useContext(ResizableContext);
  const forwardedProps = { ...props };
  delete forwardedProps.defaultSize;
  delete forwardedProps.minSize;
  delete forwardedProps.maxSize;
  delete forwardedProps._index;
  return (
    <div
      {...forwardedProps}
      data-slot="resizable-panel"
      style={{
        ...props.style,
        flexBasis: `${context?.sizes[props._index ?? 0] ?? 100}%`,
      }}
    />
  );
}

type ResizableHandleProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  _boundary?: number;
};
export function ResizableHandle({
  _boundary = 0,
  onKeyDown,
  onPointerDown,
  ...props
}: ResizableHandleProps) {
  const context = useContext(ResizableContext);
  if (!context)
    throw new Error('ResizableHandle requires a ResizablePanelGroup');
  const total =
    (context.sizes[_boundary] ?? 0) + (context.sizes[_boundary + 1] ?? 0);
  const effectiveMinimum = Math.max(
    context.minimums[_boundary]!,
    total - context.maximums[_boundary + 1]!,
  );
  const effectiveMaximum = Math.min(
    context.maximums[_boundary]!,
    total - context.minimums[_boundary + 1]!,
  );
  const move = (key: string) => {
    const current = context.sizes[_boundary] ?? 0;
    if (key === 'Home')
      return context.adjust(_boundary, effectiveMinimum - current);
    if (key === 'End')
      return context.adjust(_boundary, effectiveMaximum - current);
    const previous =
      context.orientation === 'vertical'
        ? 'ArrowUp'
        : context.direction === 'rtl'
          ? 'ArrowRight'
          : 'ArrowLeft';
    const next =
      context.orientation === 'vertical'
        ? 'ArrowDown'
        : context.direction === 'rtl'
          ? 'ArrowLeft'
          : 'ArrowRight';
    if (key === previous) context.adjust(_boundary, -5);
    else if (key === next) context.adjust(_boundary, 5);
  };
  return (
    <button
      type="button"
      {...props}
      data-slot="resizable-handle"
      role="separator"
      aria-orientation={
        context.orientation === 'horizontal' ? 'vertical' : 'horizontal'
      }
      aria-valuemin={effectiveMinimum}
      aria-valuemax={effectiveMaximum}
      aria-valuenow={Math.round(context.sizes[_boundary] ?? 0)}
      onKeyDown={(event) => {
        onKeyDown?.(event);
        if (
          !event.defaultPrevented &&
          [
            'ArrowLeft',
            'ArrowRight',
            'ArrowUp',
            'ArrowDown',
            'Home',
            'End',
          ].includes(event.key)
        ) {
          event.preventDefault();
          move(event.key);
        }
      }}
      onPointerDown={(event) => {
        onPointerDown?.(event);
        if (event.defaultPrevented) return;
        let previous =
          context.orientation === 'horizontal' ? event.clientX : event.clientY;
        const size =
          context.orientation === 'horizontal'
            ? context.root.current?.clientWidth
            : context.root.current?.clientHeight;
        if (!size) return;
        const onMove = (next: PointerEvent) => {
          const coordinate =
            context.orientation === 'horizontal' ? next.clientX : next.clientY;
          let delta = ((coordinate - previous) / size) * 100;
          previous = coordinate;
          if (
            context.orientation === 'horizontal' &&
            context.direction === 'rtl'
          )
            delta *= -1;
          context.adjust(_boundary, delta);
        };
        const onUp = () => {
          window.removeEventListener('pointermove', onMove);
          window.removeEventListener('pointerup', onUp);
        };
        window.addEventListener('pointermove', onMove);
        window.addEventListener('pointerup', onUp, { once: true });
      }}
    />
  );
}
