// packages/svelte/src/components/slider.svelte
<script lang="ts">let { value = $bindable(0), min = 0, max = 100, step = 1, disabled = false, ...rest }: { value?: number; min?: number; max?: number; step?: number; disabled?: boolean; [key: string]: unknown } = $props();</script>
<input {...rest} type="range" bind:value {min} {max} {step} {disabled} data-slot="slider" data-state={disabled ? 'disabled' : 'enabled'} />

// packages/react/src/components/slider.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';

export const Slider = /* @__PURE__ */ forwardRef<
  HTMLInputElement,
  Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> & { invalid?: boolean }
>(function Slider(
  { invalid = false, min = 0, max = 100, step = 1, ...props },
  ref,
) {
  return (
    <input
      ref={ref}
      type="range"
      min={min}
      max={max}
      step={step}
      aria-invalid={invalid || undefined}
      data-slot="slider"
      {...props}
    />
  );
});
