// packages/lit/src/components/spinner.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-spinner')
export class Spinner extends LitElement {
  @property() label = 'Loading';
  render() {
    return html`<span
      part="spinner"
      role="status"
      aria-label=${this.label}
      aria-live="polite"
      aria-busy="true"
      data-state="loading"
      ><span aria-hidden="true" data-part="indicator"
        ><slot>◌</slot></span
      ></span
    >`;
  }
}

// packages/react/src/components/spinner.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export const Spinner = /* @__PURE__ */ forwardRef<
  HTMLSpanElement,
  HTMLAttributes<HTMLSpanElement> & { label?: string }
>(function Spinner({ label = 'Loading', children, ...props }, ref) {
  return (
    <span
      ref={ref}
      role="status"
      aria-label={label}
      aria-live="polite"
      aria-busy="true"
      data-state="loading"
      {...props}
    >
      <span aria-hidden="true" data-part="indicator">
        {children ?? '◌'}
      </span>
    </span>
  );
});
