// packages/angular/src/components/tags-input.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
} from '@angular/core';

@Component({
  selector: 'simurgh-tags-input',
  standalone: true,
  template: `<div
    role="group"
    data-slot="tags-input"
    [attr.aria-label]="ariaLabel"
    [attr.data-disabled]="disabled || null"
    [attr.data-readonly]="readonly || null"
    (click)="control.focus()"
  >
    @for (tag of value; track $index) {
      <span data-slot="tags-input-tag">
        <span data-slot="tags-input-tag-text">{{ tag }}</span>
        @if (!readonly) {
          <button
            type="button"
            data-slot="tags-input-remove"
            [attr.aria-label]="removeLabel(tag)"
            [disabled]="disabled"
            (click)="remove($index, $event)"
          >
            &#215;
          </button>
        }
        @if (name) {
          <input type="hidden" [name]="name" [value]="tag" />
        }
      </span>
    }
    <input
      #control
      type="text"
      data-slot="tags-input-control"
      [value]="draft"
      [attr.aria-label]="inputLabel"
      [placeholder]="value.length ? '' : placeholder"
      [disabled]="disabled || value.length >= safeLimit"
      [readOnly]="readonly"
      [required]="required && value.length === 0"
      (input)="draft = control.value"
      (keydown)="handleKeydown($event)"
    />
  </div>`,
})
export class TagsInputComponent {
  @ViewChild('control') control?: ElementRef<HTMLInputElement>;
  private tags: string[] = [];
  @Input() set value(value: string[]) {
    this.tags = value.slice(0, 100);
  }
  get value() {
    return this.tags;
  }
  @Input() name?: string;
  @Input() disabled = false;
  @Input() readonly = false;
  @Input() required = false;
  @Input() maxTags = 20;
  @Input() placeholder = 'Add a tag';
  @Input() inputLabel = 'Add a tag';
  @Input('aria-label') ariaLabel = 'Tags';
  @Output() valueChange = new EventEmitter<string[]>();
  draft = '';
  get safeLimit() {
    return Number.isFinite(this.maxTags)
      ? Math.min(100, Math.max(1, Math.floor(this.maxTags)))
      : 20;
  }
  removeLabel(tag: string) {
    return `Remove ${tag}`;
  }
  commit(value: string[]) {
    this.value = value;
    this.valueChange.emit(value);
  }
  add() {
    const tag = this.draft.trim();
    if (
      this.disabled ||
      this.readonly ||
      !tag ||
      this.value.includes(tag) ||
      this.value.length >= this.safeLimit
    )
      return;
    this.commit([...this.value, tag]);
    this.draft = '';
  }
  remove(index: number, event?: Event) {
    event?.stopPropagation();
    if (this.disabled || this.readonly) return;
    this.commit(this.value.filter((_, itemIndex) => itemIndex !== index));
    this.control?.nativeElement.focus();
  }
  handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter' || event.key === ',') {
      event.preventDefault();
      this.add();
    } else if (event.key === 'Backspace' && !this.draft && this.value.length) {
      event.preventDefault();
      this.remove(this.value.length - 1);
    }
  }
}

// packages/react/src/components/tags-input.tsx
import { forwardRef, useRef, useState, type HTMLAttributes } from 'react';

export type TagsInputProps = Omit<
  HTMLAttributes<HTMLDivElement>,
  'defaultValue' | 'onChange'
> & {
  value?: string[];
  defaultValue?: string[];
  name?: string;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  maxTags?: number;
  placeholder?: string;
  inputLabel?: string;
  getRemoveLabel?: (tag: string) => string;
  onValueChange?: (value: string[]) => void;
};
export const TagsInput = /* @__PURE__ */ forwardRef<
  HTMLInputElement,
  TagsInputProps
>(function TagsInput(
  {
    value,
    defaultValue = [],
    name,
    disabled,
    readOnly,
    required,
    maxTags = 20,
    placeholder = 'Add a tag',
    inputLabel = 'Add a tag',
    getRemoveLabel = (tag) => `Remove ${tag}`,
    onValueChange,
    onClick,
    'aria-label': ariaLabel = 'Tags',
    ...props
  },
  forwardedRef,
) {
  const [localValue, setLocalValue] = useState(defaultValue);
  const [draft, setDraft] = useState('');
  const inputRef = useRef<HTMLInputElement | null>(null);
  const tags = (value ?? localValue).slice(0, 100);
  const limit = Number.isFinite(maxTags)
    ? Math.min(100, Math.max(1, Math.floor(maxTags)))
    : 20;
  const commit = (next: string[]) => {
    if (value === undefined) setLocalValue(next);
    onValueChange?.(next);
  };
  const add = () => {
    const tag = draft.trim();
    if (
      disabled ||
      readOnly ||
      !tag ||
      tags.includes(tag) ||
      tags.length >= limit
    )
      return;
    commit([...tags, tag]);
    setDraft('');
  };
  const remove = (index: number) => {
    if (disabled || readOnly) return;
    commit(tags.filter((_, itemIndex) => itemIndex !== index));
    inputRef.current?.focus();
  };
  return (
    <div
      {...props}
      role="group"
      aria-label={ariaLabel}
      data-slot="tags-input"
      data-disabled={disabled || undefined}
      data-readonly={readOnly || undefined}
      onClick={(event) => {
        onClick?.(event);
        inputRef.current?.focus();
      }}
    >
      {tags.map((tag, index) => (
        <span key={`${tag}-${index}`} data-slot="tags-input-tag">
          <span data-slot="tags-input-tag-text">{tag}</span>
          {!readOnly && (
            <button
              type="button"
              data-slot="tags-input-remove"
              aria-label={getRemoveLabel(tag)}
              disabled={disabled}
              onClick={(event) => {
                event.stopPropagation();
                remove(index);
              }}
            >
              {'\u00d7'}
            </button>
          )}
          {name && <input type="hidden" name={name} value={tag} />}
        </span>
      ))}
      <input
        ref={(node) => {
          inputRef.current = node;
          if (typeof forwardedRef === 'function') forwardedRef(node);
          else if (forwardedRef) forwardedRef.current = node;
        }}
        type="text"
        data-slot="tags-input-control"
        value={draft}
        aria-label={inputLabel}
        placeholder={tags.length ? undefined : placeholder}
        disabled={disabled || tags.length >= limit}
        readOnly={readOnly}
        required={required && tags.length === 0}
        onChange={(event) => setDraft(event.currentTarget.value)}
        onKeyDown={(event) => {
          if (event.key === 'Enter' || event.key === ',') {
            event.preventDefault();
            add();
          } else if (event.key === 'Backspace' && !draft && tags.length) {
            event.preventDefault();
            remove(tags.length - 1);
          }
        }}
      />
    </div>
  );
});
