// packages/svelte/src/components/toggle.svelte
<script lang="ts">
  let { pressed = $bindable(false), disabled = false, children, ...rest }: { pressed?: boolean; disabled?: boolean; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<button {...rest} type="button" aria-pressed={pressed} data-slot="toggle" data-state={pressed ? 'on' : 'off'} {disabled} onclick={() => { if (!disabled) pressed = !pressed; }}>{@render children?.()}</button>

// packages/react/src/components/toggle.tsx
import { forwardRef, useState, type ButtonHTMLAttributes } from 'react';

export const Toggle = /* @__PURE__ */ forwardRef<
  HTMLButtonElement,
  Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'> & {
    pressed?: boolean;
    defaultPressed?: boolean;
    onPressedChange?: (pressed: boolean) => void;
  }
>(function Toggle(
  {
    pressed,
    defaultPressed = false,
    onPressedChange,
    disabled,
    type = 'button',
    onClick,
    ...props
  },
  ref,
) {
  const [localPressed, setLocalPressed] = useState(defaultPressed);
  const current = pressed ?? localPressed;
  return (
    <button
      ref={ref}
      type={type}
      aria-pressed={current}
      data-state={current ? 'on' : 'off'}
      disabled={disabled}
      onClick={(event) => {
        onClick?.(event);
        if (event.defaultPrevented || disabled) return;
        const next = !current;
        if (pressed === undefined) setLocalPressed(next);
        onPressedChange?.(next);
      }}
      {...props}
    />
  );
});
