// packages/lit/src/components/alert.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-alert')
export class Alert extends LitElement {
  @property({ type: Boolean }) urgent = false;
  render() {
    return html`<div
      part="alert"
      role=${this.urgent ? 'alert' : 'status'}
      aria-live=${this.urgent ? 'assertive' : 'polite'}
      aria-atomic="true"
      data-urgent=${this.urgent ? 'true' : 'false'}
    >
      <slot></slot>
    </div>`;
  }
}

// packages/cli/assets/svelte/alert.svelte
<script lang="ts">
  let { urgent = false, children, ...props }: { urgent?: boolean; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<div {...props} role={urgent ? 'alert' : 'status'} aria-live={urgent ? 'assertive' : 'polite'} aria-atomic="true" data-urgent={urgent || undefined}>{@render children?.()}</div>
