// packages/cli/assets/lit/button-group.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-button-group')
export class ButtonGroup extends LitElement {
  @property() orientation: 'horizontal' | 'vertical' = 'horizontal';
  render() {
    return html`<div
      part="group"
      role="group"
      data-slot="button-group"
      data-orientation=${this.orientation}
      aria-orientation=${this.orientation}
    >
      <slot></slot>
    </div>`;
  }
}

// packages/cli/assets/svelte/button-group.svelte
<script lang="ts">let { orientation = 'horizontal', children, ...rest }: { orientation?: 'horizontal' | 'vertical'; children?: import('svelte').Snippet; [key: string]: unknown } = $props();</script>
<div {...rest} role="group" data-slot="button-group" data-orientation={orientation}>{@render children?.()}</div>
