// packages/lit/src/components/card.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
@customElement('simurgh-card')
export class Card extends LitElement {
  render() {
    return html`<div part="card" data-slot="card">
      <div part="header" data-slot="card-header">
        <slot name="header"></slot>
        <h3 part="title" data-slot="card-title"><slot name="title"></slot></h3>
        <p part="description" data-slot="card-description">
          <slot name="description"></slot>
        </p>
      </div>
      <div part="content" data-slot="card-content"><slot></slot></div>
      <div part="footer" data-slot="card-footer">
        <slot name="footer"></slot>
      </div>
    </div>`;
  }
}

// packages/cli/assets/svelte/card.svelte
<script lang="ts">
  let { header, title, description, children, footer, ...rest }: { header?: import('svelte').Snippet; title?: import('svelte').Snippet; description?: import('svelte').Snippet; children?: import('svelte').Snippet; footer?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<div {...rest} data-slot="card">
  {#if header || title || description}<div data-slot="card-header">{@render header?.()}{#if title}<h3 data-slot="card-title">{@render title()}</h3>{/if}{#if description}<p data-slot="card-description">{@render description()}</p>{/if}</div>{/if}
  <div data-slot="card-content">{@render children?.()}</div>
  {#if footer}<div data-slot="card-footer">{@render footer()}</div>{/if}
</div>
