// packages/angular/src/components/collapsible.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { createId } from '@simurgh-ui/core';

@Component({
  selector: 'simurgh-collapsible',
  standalone: true,
  template: `<button
      type="button"
      [disabled]="disabled"
      [attr.aria-expanded]="open"
      [attr.aria-controls]="contentId"
      (click)="toggle()"
    >
      <ng-content select="[trigger]" />
    </button>
    <div
      [id]="contentId"
      [hidden]="!open"
      [attr.data-state]="open ? 'open' : 'closed'"
    >
      <ng-content />
    </div>`,
})
export class CollapsibleComponent {
  @Input() open = false;
  @Input() disabled = false;
  @Output() openChange = new EventEmitter<boolean>();
  readonly contentId = createId('collapsible-content');
  toggle() {
    if (!this.disabled) {
      this.open = !this.open;
      this.openChange.emit(this.open);
    }
  }
}

// packages/cli/assets/svelte/collapsible.svelte
<script lang="ts">
  let { open = $bindable(false), disabled = false, trigger, children, ...rest }: { open?: boolean; disabled?: boolean; trigger?: import('svelte').Snippet; children?: import('svelte').Snippet; [key: string]: unknown } = $props();
</script>
<div {...rest} data-slot="collapsible" data-state={open ? 'open' : 'closed'}>
  <button type="button" data-slot="collapsible-trigger" aria-expanded={open} {disabled} onclick={() => open = !open}>{@render trigger?.()}</button>
  <div data-slot="collapsible-content" hidden={!open}>{@render children?.()}</div>
</div>
