// packages/react/src/components/accordion.tsx
import {
  createContext,
  useContext,
  useId,
  useState,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
  type PropsWithChildren,
} from 'react';

type AccordionContextValue = {
  open: string[];
  toggle(value: string): void;
  multiple: boolean;
  id: string;
};

const AccordionContext =
  /* @__PURE__ */ createContext<AccordionContextValue | null>(null);
const AccordionItemContext = /* @__PURE__ */ createContext<string>('');

export function Accordion({
  children,
  type = 'single',
  defaultValue = [],
}: PropsWithChildren<{
  type?: 'single' | 'multiple';
  defaultValue?: string[];
}>) {
  const [open, setOpen] = useState(defaultValue);
  const multiple = type === 'multiple';
  const toggle = (value: string) =>
    setOpen((items) =>
      items.includes(value)
        ? items.filter((item) => item !== value)
        : multiple
          ? [...items, value]
          : [value],
    );
  return (
    <AccordionContext.Provider value={{ open, toggle, multiple, id: useId() }}>
      {children}
    </AccordionContext.Provider>
  );
}
export function AccordionItem({
  value,
  ...props
}: HTMLAttributes<HTMLDivElement> & { value: string }) {
  return (
    <AccordionItemContext.Provider value={value}>
      <div {...props} />
    </AccordionItemContext.Provider>
  );
}

export function AccordionTrigger(
  props: ButtonHTMLAttributes<HTMLButtonElement>,
) {
  const context = useContext(AccordionContext)!;
  const value = useContext(AccordionItemContext);
  const open = context.open.includes(value);
  return (
    <h3>
      <button
        type="button"
        {...props}
        id={`${context.id}-trigger-${value}`}
        aria-expanded={open}
        aria-controls={`${context.id}-content-${value}`}
        onClick={(event) => {
          props.onClick?.(event);
          context.toggle(value);
        }}
      />
    </h3>
  );
}

export function AccordionContent(props: HTMLAttributes<HTMLDivElement>) {
  const context = useContext(AccordionContext)!;
  const value = useContext(AccordionItemContext);
  return context.open.includes(value) ? (
    <div
      {...props}
      role="region"
      id={`${context.id}-content-${value}`}
      aria-labelledby={`${context.id}-trigger-${value}`}
    />
  ) : null;
}

// packages/angular/src/components/accordion.ts
import { CommonModule } from '@angular/common';
import { Component, Input, signal } from '@angular/core';

@Component({
  selector: 'simurgh-accordion',
  standalone: true,
  template: `<ng-content />`,
})
export class AccordionComponent {
  @Input() multiple = false;
  readonly open = signal<string[]>([]);
  toggle(value: string) {
    this.open.update((items) =>
      items.includes(value)
        ? items.filter((x) => x !== value)
        : this.multiple
          ? [...items, value]
          : [value],
    );
  }
}

@Component({
  selector: 'simurgh-accordion-item',
  standalone: true,
  imports: [CommonModule],
  template: `<h3>
      <button type="button" [attr.aria-expanded]="expanded" (click)="toggle()">
        <ng-content select="[trigger]" />
      </button>
    </h3>
    <div *ngIf="expanded" role="region"><ng-content /></div>`,
})
export class AccordionItemComponent {
  @Input({ required: true }) value = '';
  constructor(private accordion: AccordionComponent) {}
  get expanded() {
    return this.accordion.open().includes(this.value);
  }
  toggle() {
    this.accordion.toggle(this.value);
  }
}
