// packages/svelte/src/components/button.svelte
<script lang="ts">
  type Props = {
    loading?: boolean;
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
    variant?: 'primary' | 'secondary' | 'destructive' | 'quiet';
    size?: 'sm' | 'md' | 'lg';
    fullWidth?: boolean;
    iconOnly?: boolean;
    children?: import('svelte').Snippet;
  };

  let {
    loading = false, disabled = false, type = 'button', variant = 'primary',
    size = 'md', fullWidth = false, iconOnly = false, children, ...rest
  }: Props = $props();
</script>

<button {...rest} {type} disabled={disabled || loading} aria-busy={loading || undefined}
  data-slot="button" data-state={loading ? 'loading' : 'idle'}
  data-variant={variant} data-size={size}
  data-full-width={fullWidth || undefined} data-icon-only={iconOnly || undefined}>
  {@render children?.()}
</button>

// packages/angular/src/components/button.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'simurgh-button',
  standalone: true,
  template: `<button
    [attr.type]="type"
    [disabled]="disabled || loading"
    [attr.aria-busy]="loading || null"
    data-slot="button"
    [attr.data-state]="loading ? 'loading' : 'idle'"
    [attr.data-variant]="variant"
    [attr.data-size]="size"
    [attr.data-full-width]="fullWidth || null"
    [attr.data-icon-only]="iconOnly || null"
  >
    <ng-content />
  </button>`,
})
export class ButtonComponent {
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Input() loading = false;
  @Input() disabled = false;
  @Input() variant: 'primary' | 'secondary' | 'destructive' | 'quiet' =
    'primary';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() fullWidth = false;
  @Input() iconOnly = false;
}
