// packages/react/src/components/button-group.tsx
import type { Orientation } from '@simurgh-ui/core';
import { forwardRef, type HTMLAttributes } from 'react';

export const ButtonGroup = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement> & { orientation?: Orientation }
>(function ButtonGroup(
  { orientation = 'horizontal', role = 'group', ...props },
  ref,
) {
  return (
    <div
      ref={ref}
      role={role}
      aria-orientation={orientation}
      data-slot="button-group"
      {...props}
    />
  );
});

export const ButtonGroupText = /* @__PURE__ */ forwardRef<
  HTMLSpanElement,
  HTMLAttributes<HTMLSpanElement>
>(function ButtonGroupText(props, ref) {
  return <span ref={ref} data-slot="button-group-text" {...props} />;
});

export const ButtonGroupSeparator = /* @__PURE__ */ forwardRef<
  HTMLSpanElement,
  HTMLAttributes<HTMLSpanElement> & { orientation?: Orientation }
>(function ButtonGroupSeparator(
  { orientation = 'vertical', role = 'separator', ...props },
  ref,
) {
  return (
    <span
      ref={ref}
      role={role}
      aria-orientation={orientation}
      data-slot="button-group-separator"
      {...props}
    />
  );
});

// packages/angular/src/components/button-group.ts
import type { Orientation } from '@simurgh-ui/core';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'simurgh-button-group',
  standalone: true,
  template: `<ng-content />`,
  host: {
    role: 'group',
    '[attr.aria-orientation]': 'orientation',
    '[attr.data-slot]': "'button-group'",
  },
})
export class ButtonGroupComponent {
  @Input() orientation: Orientation = 'horizontal';
}

@Component({
  selector: 'simurgh-button-group-text',
  standalone: true,
  template: `<ng-content />`,
  host: { '[attr.data-slot]': "'button-group-text'" },
})
export class ButtonGroupTextComponent {}

@Component({
  selector: 'simurgh-button-group-separator',
  standalone: true,
  template: ``,
  host: {
    role: 'separator',
    '[attr.aria-orientation]': 'orientation',
    '[attr.data-slot]': "'button-group-separator'",
  },
})
export class ButtonGroupSeparatorComponent {
  @Input() orientation: Orientation = 'vertical';
}
