// packages/lit/src/components/card.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
@customElement('simurgh-card')
export class Card extends LitElement {
  render() {
    return html`<div part="card" data-slot="card">
      <div part="header" data-slot="card-header">
        <slot name="header"></slot>
        <h3 part="title" data-slot="card-title"><slot name="title"></slot></h3>
        <p part="description" data-slot="card-description">
          <slot name="description"></slot>
        </p>
      </div>
      <div part="content" data-slot="card-content"><slot></slot></div>
      <div part="footer" data-slot="card-footer">
        <slot name="footer"></slot>
      </div>
    </div>`;
  }
}

// packages/angular/src/components/card.ts
import { Component } from '@angular/core';

@Component({
  selector: 'simurgh-card',
  standalone: true,
  template: `<ng-content />`,
  host: { 'data-slot': 'card' },
})
export class CardComponent {}

@Component({
  selector: 'simurgh-card-header',
  standalone: true,
  template: `<ng-content />`,
  host: { 'data-slot': 'card-header' },
})
export class CardHeaderComponent {}

@Component({
  selector: 'simurgh-card-title',
  standalone: true,
  template: `<h3 data-slot="card-title"><ng-content /></h3>`,
})
export class CardTitleComponent {}

@Component({
  selector: 'simurgh-card-description',
  standalone: true,
  template: `<p data-slot="card-description"><ng-content /></p>`,
})
export class CardDescriptionComponent {}

@Component({
  selector: 'simurgh-card-content',
  standalone: true,
  template: `<ng-content />`,
  host: { 'data-slot': 'card-content' },
})
export class CardContentComponent {}

@Component({
  selector: 'simurgh-card-footer',
  standalone: true,
  template: `<ng-content />`,
  host: { 'data-slot': 'card-footer' },
})
export class CardFooterComponent {}
