// packages/react/src/components/carousel.tsx
import { type Direction } from '@simurgh-ui/core';
import React, {
  createContext,
  forwardRef,
  useContext,
  useEffect,
  useState,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
} from 'react';

type CarouselContextValue = {
  index: number;
  count: number;
  loop: boolean;
  direction: Direction;
  setCount(count: number): void;
  goTo(index: number): void;
};
const CarouselContext =
  /* @__PURE__ */ createContext<CarouselContextValue | null>(null);
const useCarousel = () => {
  const context = useContext(CarouselContext);
  if (!context) throw new Error('Carousel parts require a Carousel root');
  return context;
};

export function Carousel({
  label = 'Carousel',
  direction = 'ltr',
  loop = false,
  defaultIndex = 0,
  onIndexChange,
  onKeyDown,
  children,
  ...props
}: HTMLAttributes<HTMLDivElement> & {
  label?: string;
  direction?: Direction;
  loop?: boolean;
  defaultIndex?: number;
  onIndexChange?: (index: number) => void;
}) {
  const [index, setIndex] = useState(Math.max(0, defaultIndex));
  const [count, setCount] = useState(0);
  const goTo = (next: number) => {
    if (!count) return;
    const resolved = loop
      ? (next + count) % count
      : Math.max(0, Math.min(count - 1, next));
    if (resolved !== index) {
      setIndex(resolved);
      onIndexChange?.(resolved);
    }
  };
  return (
    <CarouselContext.Provider
      value={{ index, count, loop, direction, setCount, goTo }}
    >
      <div
        {...props}
        data-slot="carousel"
        role="region"
        aria-roledescription="carousel"
        aria-label={label}
        dir={direction}
        onKeyDown={(event) => {
          onKeyDown?.(event);
          if (event.defaultPrevented) return;
          const previous = direction === 'rtl' ? 'ArrowRight' : 'ArrowLeft';
          const next = direction === 'rtl' ? 'ArrowLeft' : 'ArrowRight';
          if (event.key === previous || event.key === next) {
            event.preventDefault();
            goTo(index + (event.key === next ? 1 : -1));
          }
        }}
      >
        {children}
      </div>
    </CarouselContext.Provider>
  );
}

export function CarouselContent({
  children,
  ...props
}: HTMLAttributes<HTMLDivElement>) {
  const context = useCarousel();
  const slides = React.Children.toArray(children);
  useEffect(() => context.setCount(slides.length), [context, slides.length]);
  return (
    <div {...props} data-slot="carousel-content" aria-live="polite">
      {slides.map((child, index) =>
        React.isValidElement(child)
          ? React.cloneElement(
              child as React.ReactElement<HTMLAttributes<HTMLDivElement>>,
              {
                'aria-label': `${index + 1} of ${slides.length}`,
                'aria-hidden': context.index !== index,
                hidden: context.index !== index,
              },
            )
          : child,
      )}
    </div>
  );
}

export const CarouselItem = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function CarouselItem(props, ref) {
  return (
    <div
      {...props}
      ref={ref}
      data-slot="carousel-item"
      role="group"
      aria-roledescription="slide"
    />
  );
});

function CarouselControl({
  step,
  label,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement> & { step: -1 | 1; label: string }) {
  const context = useCarousel();
  const unavailable =
    !context.loop &&
    (step < 0 ? context.index <= 0 : context.index >= context.count - 1);
  return (
    <button
      type="button"
      {...props}
      data-slot={step < 0 ? 'carousel-previous' : 'carousel-next'}
      aria-label={label}
      disabled={unavailable || props.disabled}
      onClick={(event) => {
        props.onClick?.(event);
        if (!event.defaultPrevented) context.goTo(context.index + step);
      }}
    />
  );
}
export function CarouselPrevious(
  props: ButtonHTMLAttributes<HTMLButtonElement>,
) {
  return <CarouselControl {...props} step={-1} label="Previous slide" />;
}
export function CarouselNext(props: ButtonHTMLAttributes<HTMLButtonElement>) {
  return <CarouselControl {...props} step={1} label="Next slide" />;
}

// packages/angular/src/components/carousel.ts
import type { Direction } from '@simurgh-ui/core';
import type { OnDestroy } from '@angular/core';
import {
  Component,
  EventEmitter,
  HostBinding,
  HostListener,
  inject,
  Input,
  Output,
} from '@angular/core';

@Component({
  selector: 'simurgh-carousel',
  standalone: true,
  template: `<ng-content />`,
  host: {
    'data-slot': 'carousel',
    role: 'region',
    'aria-roledescription': 'carousel',
    '[attr.aria-label]': 'label',
    '[attr.dir]': 'direction',
    tabindex: '0',
  },
})
export class CarouselComponent {
  @Input() label = 'Carousel';
  @Input() direction: Direction = 'ltr';
  @Input() loop = false;
  @Output() indexChange = new EventEmitter<number>();
  index = 0;
  readonly items: CarouselItemComponent[] = [];

  @Input() set defaultIndex(value: number) {
    this.index = Math.max(0, value);
  }
  get count() {
    return this.items.length;
  }
  register(item: CarouselItemComponent) {
    this.items.push(item);
  }
  unregister(item: CarouselItemComponent) {
    const index = this.items.indexOf(item);
    if (index >= 0) this.items.splice(index, 1);
    this.index = Math.min(this.index, Math.max(0, this.count - 1));
  }
  itemIndex(item: CarouselItemComponent) {
    return this.items.indexOf(item);
  }
  goTo(next: number) {
    if (!this.count) return;
    const resolved = this.loop
      ? (next + this.count) % this.count
      : Math.max(0, Math.min(this.count - 1, next));
    if (resolved !== this.index) {
      this.index = resolved;
      this.indexChange.emit(resolved);
    }
  }
  @HostListener('keydown', ['$event']) onKeydown(event: KeyboardEvent) {
    const previous = this.direction === 'rtl' ? 'ArrowRight' : 'ArrowLeft';
    const next = this.direction === 'rtl' ? 'ArrowLeft' : 'ArrowRight';
    if (event.key === previous || event.key === next) {
      event.preventDefault();
      this.goTo(this.index + (event.key === next ? 1 : -1));
    }
  }
}

@Component({
  selector: 'simurgh-carousel-content',
  standalone: true,
  template: `<ng-content />`,
  host: { 'data-slot': 'carousel-content', 'aria-live': 'polite' },
})
export class CarouselContentComponent {}

@Component({
  selector: 'simurgh-carousel-item',
  standalone: true,
  template: `<ng-content />`,
  host: {
    'data-slot': 'carousel-item',
    role: 'group',
    'aria-roledescription': 'slide',
  },
})
export class CarouselItemComponent implements OnDestroy {
  private carousel = inject(CarouselComponent);
  constructor() {
    this.carousel.register(this);
  }
  get position() {
    return this.carousel.itemIndex(this);
  }
  @HostBinding('attr.aria-label') get label() {
    return `${this.position + 1} of ${this.carousel.count}`;
  }
  @HostBinding('attr.aria-hidden') get ariaHidden() {
    return this.carousel.index !== this.position;
  }
  @HostBinding('attr.hidden') get hidden() {
    return this.carousel.index === this.position ? null : '';
  }
  ngOnDestroy() {
    this.carousel.unregister(this);
  }
}

function carouselUnavailable(carousel: CarouselComponent, step: -1 | 1) {
  return (
    !carousel.loop &&
    (step < 0 ? carousel.index <= 0 : carousel.index >= carousel.count - 1)
  );
}

@Component({
  selector: 'simurgh-carousel-previous',
  standalone: true,
  template: `<button
    type="button"
    data-slot="carousel-previous"
    aria-label="Previous slide"
    [disabled]="unavailable"
    (click)="carousel.goTo(carousel.index - 1)"
  >
    <ng-content />
  </button>`,
})
export class CarouselPreviousComponent {
  readonly carousel = inject(CarouselComponent);
  get unavailable() {
    return carouselUnavailable(this.carousel, -1);
  }
}

@Component({
  selector: 'simurgh-carousel-next',
  standalone: true,
  template: `<button
    type="button"
    data-slot="carousel-next"
    aria-label="Next slide"
    [disabled]="unavailable"
    (click)="carousel.goTo(carousel.index + 1)"
  >
    <ng-content />
  </button>`,
})
export class CarouselNextComponent {
  readonly carousel = inject(CarouselComponent);
  get unavailable() {
    return carouselUnavailable(this.carousel, 1);
  }
}
