// packages/react/src/components/chart.tsx
import {
  areaPath,
  bandScale,
  chartDomain,
  chartLayout,
  chartSummary,
  chartValue,
  linePath,
  linearScale,
  logScale,
  minMaxDecimate,
  numericValue,
  pieArcs,
  radarPoints,
  stackChartValues,
  stackedAreaPath,
  type ChartAccessibility,
  type ChartAccessor,
  type ChartDomain,
  type ChartRenderMode,
  type ChartScaleType,
  type ChartSeries,
  type ChartSeriesType,
  type ChartValue,
} from '@simurgh-ui/core/charts';
import type { CanvasMark } from '@simurgh-ui/core/chart-canvas';
import type { ChartStream } from '@simurgh-ui/core/chart-stream';
import {
  createContext,
  useContext,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type HTMLAttributes,
  type ReactNode,
  type SVGAttributes,
} from 'react';

export type ChartProps<T> = Omit<HTMLAttributes<HTMLElement>, 'title'> & {
  data?: readonly T[];
  stream?: ChartStream<string>;
  x?: ChartAccessor<T>;
  y?: ChartAccessor<T, number>;
  series?: readonly ChartSeries<T>[];
  accessibility: ChartAccessibility;
  width?: number;
  height?: number;
  xScale?: ChartScaleType;
  yScale?: Exclude<ChartScaleType, 'band'>;
  xDomain?: ChartDomain;
  yDomain?: ChartDomain;
  renderMode?: ChartRenderMode;
  canvasThreshold?: number;
  hiddenSeries?: readonly string[];
  defaultHiddenSeries?: readonly string[];
  onHiddenSeriesChange?: (series: string[]) => void;
  emptyContent?: ReactNode;
  orientation?: 'vertical' | 'horizontal';
  innerRadius?: number;
};

type PreparedPoint<T> = {
  datum: T;
  index: number;
  x: number;
  y: number;
  xValue: ChartValue;
  yValue: number;
  radius: number;
  y0: number;
};
type PreparedSeries<T> = ChartSeries<T> & { points: PreparedPoint<T>[]; type: ChartSeriesType };
type ChartContextValue = { width: number; height: number };
const ChartContext = createContext<ChartContextValue | null>(null);

const colors = Array.from({ length: 10 }, (_, index) => `hsl(var(--simurgh-chart-${index + 1}))`);
const axisNumberFormatter = new Intl.NumberFormat('en-US');

function useChartRows<T>(data: readonly T[] | undefined, stream: ChartStream<string> | undefined, width: number): readonly T[] {
  const [version, setVersion] = useState(0);
  useEffect(() => stream?.subscribe(() => setVersion((value) => value + 1)), [stream]);
  return useMemo(() => {
    if (data && stream) throw new TypeError('Chart accepts either data or stream, not both.');
    if (!stream) return data ?? [];
    const snapshot = stream.snapshot();
    const limit = Math.max(2, Math.floor(width * 2));
    const step = Math.max(1, Math.ceil(snapshot.length / limit));
    const indexes = Array.from({ length: Math.ceil(snapshot.length / step) }, (_, index) => index * step);
    if (snapshot.length && indexes.at(-1) !== snapshot.length - 1) indexes.push(snapshot.length - 1);
    return indexes.map((index) => Object.fromEntries(stream.dimensions.map((key) => [key, snapshot.columns[key]![index]])) as T);
  }, [data, stream, version, width]);
}

export function ChartRoot({ width = 640, height = 360, children, ...props }: HTMLAttributes<HTMLElement> & ChartContextValue) {
  return (
    <ChartContext.Provider value={{ width, height }}>
      <figure className="simurgh-chart" data-slot="chart" {...props}>{children}</figure>
    </ChartContext.Provider>
  );
}
export function ChartPlot(props: SVGAttributes<SVGSVGElement>) {
  const context = useContext(ChartContext);
  return <svg viewBox={`0 0 ${context?.width ?? 640} ${context?.height ?? 360}`} data-part="plot" {...props} />;
}
export function ChartGrid(props: SVGAttributes<SVGGElement>) { return <g data-part="grid" {...props} />; }
export function ChartXAxis(props: SVGAttributes<SVGGElement>) { return <g data-part="x-axis" {...props} />; }
export function ChartYAxis(props: SVGAttributes<SVGGElement>) { return <g data-part="y-axis" {...props} />; }
export function ChartLegend(props: HTMLAttributes<HTMLDivElement>) { return <div data-part="legend" {...props} />; }
export function ChartTooltip(props: HTMLAttributes<HTMLDivElement>) { return <div role="tooltip" data-part="tooltip" {...props} />; }
export function ChartCrosshair(props: SVGAttributes<SVGGElement>) { return <g data-part="crosshair" {...props} />; }
export function ChartBrush(props: SVGAttributes<SVGRectElement>) { return <rect data-part="brush" {...props} />; }

export function ChartDataTable<T>({ data, columns, pageSize = 50 }: {
  data: readonly T[];
  columns: readonly { label: string; value: ChartAccessor<T> }[];
  pageSize?: number;
}) {
  const [page, setPage] = useState(0);
  const size = Math.max(1, pageSize);
  const pages = Math.max(1, Math.ceil(data.length / size));
  const current = Math.min(page, pages - 1);
  return (
    <div data-part="data-table">
      <table><thead><tr>{columns.map((column) => <th key={column.label} scope="col">{column.label}</th>)}</tr></thead>
        <tbody>{data.slice(current * size, current * size + size).map((datum, row) => (
          <tr key={current * size + row}>{columns.map((column) => <td key={column.label}>{String(chartValue(datum, column.value, current * size + row) ?? '')}</td>)}</tr>
        ))}</tbody></table>
      {pages > 1 && <nav aria-label="Chart data pages"><button type="button" disabled={!current} onClick={() => setPage(current - 1)}>Previous</button><span>{current + 1} / {pages}</span><button type="button" disabled={current + 1 >= pages} onClick={() => setPage(current + 1)}>Next</button></nav>}
    </div>
  );
}

function CartesianChart<T>({ kind, ...props }: ChartProps<T> & { kind: ChartSeriesType | 'combo' }) {
  const {
    data: inputData, stream, x = ((_, index) => index), y, series, accessibility, width = 640, height = 360,
    xScale = 'linear', yScale = 'linear', xDomain, yDomain, renderMode = 'auto', canvasThreshold = 2000,
    hiddenSeries: controlledHiddenSeries, defaultHiddenSeries = [], onHiddenSeriesChange, emptyContent = 'No chart data', orientation = 'vertical', ...native
  } = props;
  const [uncontrolledHiddenSeries, setUncontrolledHiddenSeries] = useState<readonly string[]>(defaultHiddenSeries);
  const hiddenSeries = controlledHiddenSeries ?? uncontrolledHiddenSeries;
  const data = useChartRows(inputData, stream, width);
  const titleId = `${useId()}-title`;
  const descriptionId = `${titleId}-description`;
  const layout = chartLayout(width, height);
  const definitions = useMemo<ChartSeries<T>[]>(() => series?.length ? [...series] : y ? [{ id: 'value', y, x, type: kind === 'combo' ? 'line' : kind }] : [], [series, y, x, kind]);
  const active = definitions.filter((item) => !hiddenSeries.includes(item.id));
  const unstacked = active.flatMap((definition) => data.map((datum, index) => {
    const xValue = chartValue(datum, definition.x ?? x, index);
    const yValue = numericValue(chartValue(datum, definition.y, index));
    const numericX = numericValue(xValue);
    return yValue == null || xValue == null || (xScale !== 'band' && numericX == null) || (yScale === 'log' && yValue <= 0)
      ? null : { datum, index, xValue, numericX: numericX ?? index, yValue, radius: numericValue(definition.radius ? chartValue(datum, definition.radius, index) : 4) ?? 4, definition };
  }).filter((item): item is NonNullable<typeof item> => item != null));
  const raw = stackChartValues(unstacked.map((item) => ({ ...item, stack: item.definition.stack, x: item.xValue, value: item.yValue })));
  const categories = raw.map((item) => item.xValue);
  const resolvedX = xDomain ?? chartDomain(raw.map((item) => item.numericX)) ?? [0, 1];
  const resolvedY = yDomain ?? chartDomain(raw.flatMap((item) => [item.start, item.end]), { includeZero: active.some((item) => item.type === 'bar' || kind === 'bar'), log: yScale === 'log' }) ?? [0, 1];
  const horizontalBars = kind === 'bar' && orientation === 'horizontal';
  const xBand = xScale === 'band' ? bandScale(categories, horizontalBars ? [layout.top, layout.top + layout.plotHeight] : [layout.left, layout.left + layout.plotWidth]) : null;
  const numericXMap = (xScale === 'log' ? logScale : linearScale)(resolvedX, [layout.left, layout.left + layout.plotWidth]);
  const xMap = xBand
    ? (value: ChartValue) => xBand.map(value) + xBand.bandwidth / 2
    : (value: ChartValue) => numericXMap(numericValue(value) ?? resolvedX[0]);
  const yMap = (yScale === 'log' ? logScale : linearScale)(resolvedY, [layout.top + layout.plotHeight, layout.top]);
  const horizontalValueMap = linearScale(resolvedY, [layout.left, layout.left + layout.plotWidth]);
  const prepared: PreparedSeries<T>[] = active.map((definition) => ({ ...definition, type: definition.type ?? (kind === 'combo' ? 'line' : kind), points: raw.filter((item) => item.definition === definition).map((item) => horizontalBars
    ? ({ ...item, x: horizontalValueMap(item.end), y: xBand ? xBand.map(item.xValue) + xBand.bandwidth / 2 : xMap(item.xValue), y0: horizontalValueMap(item.start) })
    : ({ ...item, x: xMap(item.xValue), y: yMap(item.end), y0: yMap(item.start) })) }));
  const pointCount = prepared.reduce((sum, item) => sum + item.points.length, 0);
  const useCanvas = renderMode === 'canvas' || (renderMode === 'auto' && pointCount > canvasThreshold);
  const [focus, setFocus] = useState(0);
  const flat = prepared.flatMap((item) => item.points.map((point) => ({ ...point, series: item })));
  const canvas = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    if (!useCanvas || !canvas.current) return;
    let current = true;
    void import('@simurgh-ui/core/chart-canvas').then(({ drawChartCanvas }) => {
      if (!current || !canvas.current) return;
      const context = canvas.current.getContext('2d');
      if (!context) return;
      const marks: CanvasMark[] = prepared.flatMap<CanvasMark>((item, seriesIndex) => {
        const color = item.color ?? colors[seriesIndex % colors.length]!;
        const points = (item.type === 'line' || item.type === 'area') ? minMaxDecimate(item.points, layout.plotWidth) : item.points;
        if (item.type === 'line') return [{ type: 'line' as const, points: points.map((point) => [point.x, point.y] as const), color }];
        if (item.type === 'area') return [{ type: 'area' as const, points: points.map((point) => [point.x, point.y] as const), baseline: item.stack && points[0] ? points[0].y0 : yMap(0), color, opacity: 0.3 }];
        if (item.type === 'bar') return points.map((point) => {
          const origin = item.stack ? point.y0 : horizontalBars ? horizontalValueMap(0) : yMap(0);
          return horizontalBars
            ? { type: 'rect' as const, x: Math.min(point.x, origin), y: point.y - (xBand?.bandwidth ?? 8) / 2, width: Math.abs(point.x - origin), height: xBand?.bandwidth ?? 8, color }
            : { type: 'rect' as const, x: point.x - (xBand?.bandwidth ?? 8) / 2, y: Math.min(point.y, origin), width: xBand?.bandwidth ?? 8, height: Math.abs(point.y - origin), color };
        });
        return points.map((point) => ({ type: 'point' as const, x: point.x, y: point.y, radius: item.type === 'bubble' ? point.radius : 3, color }));
      });
      drawChartCanvas(context, marks, width, height, window.devicePixelRatio || 1);
    });
    return () => { current = false; };
  }, [useCanvas, prepared, layout.plotWidth, width, height]);
  const summary = chartSummary(flat.map((item) => item.yValue));
  const decorative = 'decorative' in accessibility && accessibility.decorative;
  const table = !decorative && accessibility.table;
  const toggleSeries = (id: string) => {
    const next = hiddenSeries.includes(id) ? hiddenSeries.filter((item) => item !== id) : [...hiddenSeries, id];
    if (controlledHiddenSeries === undefined) setUncontrolledHiddenSeries(next);
    onHiddenSeriesChange?.(next);
  };
  if (!flat.length) return <figure className="simurgh-chart" data-slot="chart" data-state="empty" {...native}>
    {!decorative && <><figcaption id={titleId}>{accessibility.title}</figcaption><p id={descriptionId} data-part="description">{accessibility.description}</p></>}
    <div data-part="empty">{emptyContent}</div>
    <div data-part="legend">{definitions.map((item, index) => <button type="button" key={item.id} aria-pressed={!hiddenSeries.includes(item.id)} onClick={() => toggleSeries(item.id)}><span style={{ background: item.color ?? colors[index % colors.length] }} />{item.label ?? item.id}</button>)}</div>
  </figure>;
  const focused = flat[Math.min(focus, flat.length - 1)];
  const focusFromPointer = (event: Pick<React.MouseEvent<HTMLDivElement>, 'currentTarget' | 'clientX' | 'clientY'>) => {
    const bounds = event.currentTarget.getBoundingClientRect();
    if (!bounds.width || !bounds.height) return;
    const x = ((event.clientX - bounds.left) / bounds.width) * width;
    const y = ((event.clientY - bounds.top) / bounds.height) * height;
    let nearest = 0;
    let distance = Number.POSITIVE_INFINITY;
    flat.forEach((point, index) => {
      const nextDistance = Math.hypot(point.x - x, point.y - y);
      if (nextDistance < distance) {
        distance = nextDistance;
        nearest = index;
      }
    });
    setFocus(nearest);
  };
  const ticks = Array.from({ length: 5 }, (_, index) => resolvedY[0] + ((resolvedY[1] - resolvedY[0]) * index) / 4);
  return (
    <figure className="simurgh-chart" data-slot="chart" data-renderer={useCanvas ? 'canvas' : 'svg'} dir={native.dir} aria-labelledby={decorative ? undefined : titleId} aria-describedby={decorative ? undefined : descriptionId} aria-hidden={decorative || undefined} {...native}>
      {!decorative && <><figcaption id={titleId}>{accessibility.title}</figcaption><p id={descriptionId} data-part="description">{accessibility.description} {summary}</p></>}
      <div data-part="viewport" style={{ aspectRatio: `${width} / ${height}` }} onMouseMove={focusFromPointer}>
        {useCanvas && <canvas ref={canvas} width={width} height={height} aria-hidden="true" />}
        <svg viewBox={`0 0 ${width} ${height}`} data-part="plot" aria-hidden="true">
          <g data-part="grid">{ticks.map((tick) => <line key={tick} x1={layout.left} x2={layout.left + layout.plotWidth} y1={yMap(tick)} y2={yMap(tick)} />)}</g>
          <g data-part="y-axis">{ticks.map((tick) => <text key={tick} x={layout.left - 8} y={yMap(tick)}>{axisNumberFormatter.format(tick)}</text>)}</g>
          {!useCanvas && prepared.map((item, seriesIndex) => <SeriesMarks key={item.id} item={item} index={seriesIndex} baseline={horizontalBars ? horizontalValueMap(0) : yMap(0)} bandwidth={xBand?.bandwidth ?? 8} orientation={orientation} />)}
          {focused && <g data-part="crosshair"><line x1={focused.x} x2={focused.x} y1={layout.top} y2={layout.top + layout.plotHeight} /><circle cx={focused.x} cy={focused.y} r="4" /></g>}
        </svg>
        <button type="button" data-part="keyboard-target" aria-label="Explore chart data" onKeyDown={(event) => {
          if (event.key === 'Home') setFocus(0); else if (event.key === 'End') setFocus(flat.length - 1); else if (['ArrowLeft', 'ArrowUp'].includes(event.key)) setFocus((value) => Math.max(0, value - 1)); else if (['ArrowRight', 'ArrowDown'].includes(event.key)) setFocus((value) => Math.min(flat.length - 1, value + 1)); else return;
          event.preventDefault();
        }} />
        {focused && <div role="tooltip" data-part="tooltip">{focused.series.label ?? focused.series.id}: {focused.yValue}</div>}
      </div>
      <div data-part="legend">{definitions.map((item, index) => <button type="button" key={item.id} aria-pressed={!hiddenSeries.includes(item.id)} onClick={() => toggleSeries(item.id)}><span style={{ background: item.color ?? colors[index % colors.length] }} />{item.label ?? item.id}</button>)}</div>
      {table && <ChartDataTable data={data} pageSize={typeof table === 'object' ? table.pageSize ?? 50 : 50} columns={[{ label: 'Category', value: x }, ...definitions.map((item) => ({ label: item.label ?? item.id, value: item.y }))]} />}
    </figure>
  );
}

function SeriesMarks<T>({ item, index, baseline, bandwidth, orientation }: { item: PreparedSeries<T>; index: number; baseline: number; bandwidth: number; orientation: string }) {
  const color = item.color ?? colors[index % colors.length];
  const points = item.points.map((point) => [point.x, point.y] as const);
  if (item.type === 'line') return <path data-part="series" data-series={item.id} d={linePath(points)} fill="none" stroke={color} />;
  if (item.type === 'area') return <path data-part="series" data-series={item.id} d={item.stack ? stackedAreaPath(item.points.map((point) => ({ x: point.x, y0: point.y0, y1: point.y }))) : areaPath(points, baseline)} fill={color} stroke={color} />;
  if (item.type === 'bar') return <g data-part="series" data-series={item.id}>{item.points.map((point) => { const origin = item.stack ? point.y0 : baseline; return orientation === 'horizontal'
    ? <rect key={point.index} x={Math.min(point.x, origin)} y={point.y - bandwidth / 2} width={Math.abs(origin - point.x)} height={bandwidth} fill={color} />
    : <rect key={point.index} x={point.x - bandwidth / 2} y={Math.min(point.y, origin)} width={bandwidth} height={Math.abs(origin - point.y)} fill={color} />; })}</g>;
  if (item.type === 'heatmap') return <g data-part="series" data-series={item.id}>{item.points.map((point) => <rect key={point.index} x={point.x - 5} y={point.y - 5} width="10" height="10" fill={color} style={{ opacity: Math.min(1, Math.max(0.15, point.radius / 10)) }} />)}</g>;
  return <g data-part="series" data-series={item.id}>{item.points.map((point) => <circle key={point.index} cx={point.x} cy={point.y} r={item.type === 'bubble' ? point.radius : 3} fill={color} />)}</g>;
}

function PolarChart<T>({ donut = false, ...props }: ChartProps<T> & { donut?: boolean }) {
  const { data: inputData, stream, y, series, accessibility, width = 360, height = 360, innerRadius, emptyContent = 'No chart data', ...native } = props;
  const data = useChartRows(inputData, stream, width);
  const value = y ?? series?.[0]?.y;
  if (!value) throw new TypeError('Pie and donut charts require a y accessor or series.');
  const radius = Math.max(0, Math.min(width, height) / 2 - 16);
  const arcs = pieArcs(data, value, radius, donut ? innerRadius ?? radius * 0.55 : innerRadius ?? 0);
  const titleId = `${useId()}-title`;
  const decorative = 'decorative' in accessibility && accessibility.decorative;
  if (!arcs.length) return <figure className="simurgh-chart" data-state="empty" {...native}>{emptyContent}</figure>;
  return <figure className="simurgh-chart" data-slot="chart" aria-labelledby={decorative ? undefined : titleId} aria-hidden={decorative || undefined} {...native}>
    {!decorative && <figcaption id={titleId}>{accessibility.title}</figcaption>}
    <svg viewBox={`${-width / 2} ${-height / 2} ${width} ${height}`} data-part="plot" aria-hidden="true">{arcs.map((arc, index) => <path key={arc.index} data-part="series" d={arc.path} fill={colors[index % colors.length]} />)}</svg>
    {!decorative && <p data-part="description">{accessibility.description} {chartSummary(arcs.map((arc) => arc.value), 'Slices')}</p>}
  </figure>;
}

export function LineChart<T>(props: ChartProps<T>) { return <CartesianChart {...props} kind="line" />; }
export function AreaChart<T>(props: ChartProps<T>) { return <CartesianChart {...props} kind="area" />; }
export function BarChart<T>(props: ChartProps<T>) { return <CartesianChart {...props} kind="bar" xScale={props.xScale ?? 'band'} />; }
export function ScatterChart<T>(props: ChartProps<T>) { return <CartesianChart {...props} kind="scatter" />; }
export function BubbleChart<T>(props: ChartProps<T>) { return <CartesianChart {...props} kind="bubble" />; }
export function HeatmapChart<T>(props: ChartProps<T>) { return <CartesianChart {...props} kind="heatmap" />; }
export function ComboChart<T>(props: ChartProps<T>) { return <CartesianChart {...props} kind="combo" />; }
export function PieChart<T>(props: ChartProps<T>) { return <PolarChart {...props} />; }
export function DonutChart<T>(props: ChartProps<T>) { return <PolarChart {...props} donut />; }
export function RadarChart<T>(props: ChartProps<T>) {
  const { data: inputData, stream, y, series, accessibility, width = 360, height = 360, emptyContent = 'No chart data', ...native } = props;
  const data = useChartRows(inputData, stream, width);
  const value = y ?? series?.[0]?.y;
  const values = value ? data.map((datum, index) => numericValue(chartValue(datum, value, index))).filter((item): item is number => item != null) : [];
  const decorative = 'decorative' in accessibility && accessibility.decorative;
  return <figure className="simurgh-chart" data-slot="chart" data-state={values.length ? undefined : 'empty'} aria-hidden={decorative || undefined} {...native}>{values.length ? <svg viewBox={`${-width / 2} ${-height / 2} ${width} ${height}`} data-part="plot" aria-hidden="true"><polygon data-part="series" points={radarPoints(values, Math.min(width, height) / 2 - 24)} fill={colors[0]} stroke={colors[0]} /></svg> : emptyContent}{!decorative && <><figcaption>{accessibility.title}</figcaption><p data-part="description">{accessibility.description} {chartSummary(values)}</p></>}</figure>;
}

// packages/angular/src/components/chart.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  Directive,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
  ChangeDetectorRef,
} from '@angular/core';
import type { AfterViewChecked, OnDestroy } from '@angular/core';
import {
  areaPath,
  bandScale,
  chartDomain,
  chartLayout,
  chartSummary,
  chartValue,
  linePath,
  linearScale,
  logScale,
  numericValue,
  pieArcs,
  radarPoints,
  stackChartValues,
  stackedAreaPath,
  type ChartAccessibility,
  type ChartAccessor,
  type ChartSeries,
  type ChartSeriesType,
  type ChartDomain,
} from '@simurgh-ui/core/charts';
import { clampDomain, domainFromSelection, zoomDomain } from '@simurgh-ui/core/chart-interactions';
import type { CanvasMark } from '@simurgh-ui/core/chart-canvas';
import type { ChartStream } from '@simurgh-ui/core/chart-stream';

type Datum = Record<PropertyKey, unknown>;
type Mark = {
  id: string;
  type: ChartSeriesType;
  color: string;
  path?: string;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  radius?: number;
};
const colors = Array.from({ length: 10 }, (_, index) => `hsl(var(--simurgh-chart-${index + 1}))`);

const template = `
  <figcaption *ngIf="!decorative">{{ accessibility.title }}</figcaption>
  <p *ngIf="!decorative" data-part="description">{{ accessibility.description }} {{ model.summary }}</p>
  <div data-part="viewport" [style.aspect-ratio]="width + ' / ' + height" (wheel)="onWheel($event)">
    <canvas #canvas *ngIf="model.useCanvas" [attr.width]="width" [attr.height]="height" aria-hidden="true"></canvas>
    <svg [attr.viewBox]="'0 0 ' + width + ' ' + height" data-part="plot" aria-hidden="true">
      <ng-container *ngIf="!model.useCanvas">
        <ng-container *ngFor="let mark of model.marks">
          <path *ngIf="mark.path" data-part="series" [attr.data-series]="mark.id" [attr.d]="mark.path" [attr.fill]="mark.type === 'line' ? 'none' : mark.color" [attr.stroke]="mark.color"></path>
          <rect *ngIf="mark.type === 'bar' || mark.type === 'heatmap'" data-part="series" [attr.x]="mark.x" [attr.y]="mark.y" [attr.width]="mark.width" [attr.height]="mark.height" [attr.fill]="mark.color"></rect>
          <circle *ngIf="mark.type === 'scatter' || mark.type === 'bubble'" data-part="series" [attr.cx]="mark.x" [attr.cy]="mark.y" [attr.r]="mark.radius" [attr.fill]="mark.color"></circle>
        </ng-container>
      </ng-container>
    </svg>
    <button type="button" data-part="keyboard-target" aria-label="Explore chart data" (keydown)="onKeydown($event)"></button>
    <div *ngIf="model.tooltip" role="tooltip" data-part="tooltip">{{ model.tooltip }}</div>
  </div>
  <div data-part="legend">
    <button *ngFor="let item of model.legend; let index = index" type="button" [attr.aria-pressed]="!effectiveHiddenSeries.includes(item.id)" (click)="toggleSeries(item.id)">
      <span [style.background]="item.color"></span>{{ item.label }}
    </button>
  </div>
  <div *ngIf="tableEnabled" data-part="data-table">
    <table>
      <thead><tr><th scope="col">Category</th><th *ngFor="let item of model.legend" scope="col">{{ item.label }}</th></tr></thead>
      <tbody><tr *ngFor="let datum of tableRows; let row = index"><td>{{ tableValue(datum, xAccessor, row) }}</td><td *ngFor="let item of activeSeries">{{ tableValue(datum, item.y, row) }}</td></tr></tbody>
    </table>
    <nav *ngIf="tablePages > 1" aria-label="Chart data pages"><button type="button" [disabled]="tablePage === 0" (click)="tablePage = tablePage - 1">Previous</button><span>{{ tablePage + 1 }} / {{ tablePages }}</span><button type="button" [disabled]="tablePage + 1 >= tablePages" (click)="tablePage = tablePage + 1">Next</button></nav>
  </div>
  <div *ngIf="!model.marks.length" data-part="empty">{{ emptyContent }}</div>
`;

@Directive()
export abstract class ChartBaseComponent implements AfterViewChecked, OnDestroy {
  @Input() data: readonly Datum[] = [];
  private streamValue: ChartStream<string> | undefined;
  private unsubscribeStream: (() => void) | undefined;
  @Input() set stream(value: ChartStream<string> | undefined) {
    this.unsubscribeStream?.();
    this.streamValue = value;
    this.unsubscribeStream = value?.subscribe(() => this.changeDetector?.markForCheck());
  }
  get stream() { return this.streamValue; }
  @Input() x?: ChartAccessor<Datum>;
  @Input() y?: ChartAccessor<Datum, number>;
  @Input() series?: readonly ChartSeries<Datum>[];
  @Input({ required: true }) accessibility!: ChartAccessibility;
  @Input() width = 640;
  @Input() height = 360;
  @Input() xScale: 'linear' | 'time' | 'band' | 'log' = 'linear';
  @Input() yScale: 'linear' | 'time' | 'log' = 'linear';
  @Input() xDomain?: ChartDomain;
  @Input() yDomain?: ChartDomain;
  @Input() viewport?: { x?: ChartDomain; y?: ChartDomain };
  @Input() defaultViewport: { x?: ChartDomain; y?: ChartDomain } = {};
  @Input() interaction?: { zoom?: boolean | 'x' | 'y' | 'xy'; pan?: boolean | 'x' | 'y' | 'xy'; brush?: boolean | 'x' | 'y' | 'xy' };
  @Input() renderMode: 'auto' | 'svg' | 'canvas' = 'auto';
  @Input() canvasThreshold = 2000;
  @Input() hiddenSeries?: readonly string[];
  @Input() defaultHiddenSeries: readonly string[] = [];
  @Input() innerRadius?: number;
  @Input() emptyContent = 'No chart data';
  @Output() readonly hiddenSeriesChange = new EventEmitter<string[]>();
  @Output() readonly viewportChange = new EventEmitter<{ x?: ChartDomain; y?: ChartDomain }>();
  @ViewChild('canvas') canvas?: ElementRef<HTMLCanvasElement>;
  abstract readonly kind: ChartSeriesType | 'combo' | 'pie' | 'donut';
  focused = 0;
  tablePage = 0;
  private uncontrolledHiddenSeries?: readonly string[];
  private uncontrolledViewport: { x?: ChartDomain; y?: ChartDomain } = {};
  private drawn = '';
  constructor(private readonly changeDetector?: ChangeDetectorRef) {}

  get effectiveHiddenSeries() { return this.hiddenSeries ?? this.uncontrolledHiddenSeries ?? this.defaultHiddenSeries; }
  get effectiveViewport() { return this.viewport ?? this.uncontrolledViewport; }

  get decorative() {
    return 'decorative' in this.accessibility && this.accessibility.decorative;
  }
  get xAccessor(): ChartAccessor<Datum> { return this.x ?? ((_: Datum, index: number) => index); }
  get activeSeries(): readonly ChartSeries<Datum>[] { return (this.series?.length ? this.series : this.y ? [{ id: 'value', y: this.y, x: this.xAccessor, type: this.kind === 'combo' ? 'line' : this.kind as ChartSeriesType }] : []).filter((item) => !this.effectiveHiddenSeries.includes(item.id)); }
  get tableEnabled() { return !this.decorative && 'table' in this.accessibility && Boolean(this.accessibility.table); }
  get tablePageSize() { const table = 'table' in this.accessibility ? this.accessibility.table : false; return typeof table === 'object' ? table.pageSize ?? 50 : 50; }
  get rows(): readonly Datum[] {
    if (!this.streamValue) return this.data;
    if (this.data.length) throw new TypeError('Chart accepts either data or stream, not both.');
    const snapshot = this.streamValue.snapshot();
    const limit = Math.max(2, Math.floor(this.width * 2));
    const step = Math.max(1, Math.ceil(snapshot.length / limit));
    const indexes = Array.from({ length: Math.ceil(snapshot.length / step) }, (_, index) => index * step);
    if (snapshot.length && indexes.at(-1) !== snapshot.length - 1) indexes.push(snapshot.length - 1);
    return indexes.map((index) => Object.fromEntries(this.streamValue!.dimensions.map((key) => [key, snapshot.columns[key]![index]])) as Datum);
  }
  get tablePages() { return Math.max(1, Math.ceil(this.rows.length / this.tablePageSize)); }
  get tableRows() { return this.rows.slice(this.tablePage * this.tablePageSize, this.tablePage * this.tablePageSize + this.tablePageSize); }
  tableValue(datum: Datum, value: ChartAccessor<Datum>, row: number) { return String(chartValue(datum, value, this.tablePage * this.tablePageSize + row) ?? ''); }

  get model() {
    if (this.kind === 'pie' || this.kind === 'donut') return this.polarModel();
    const layout = chartLayout(this.width, this.height);
    const xAccessor = this.xAccessor;
    const definitions: readonly ChartSeries<Datum>[] = this.series?.length
      ? this.series
      : this.y ? [{ id: 'value', y: this.y, x: xAccessor, type: this.kind === 'combo' ? 'line' : this.kind }] : [];
    const active = this.activeSeries;
    const unstacked = active.flatMap((definition) => this.rows.map((datum, index) => {
      const xValue = chartValue(datum, definition.x ?? xAccessor, index);
      const yValue = numericValue(chartValue(datum, definition.y, index));
      const numericX = numericValue(xValue);
      return xValue == null || yValue == null || (this.xScale !== 'band' && numericX == null) || (this.yScale === 'log' && yValue <= 0)
        ? null : { index, xValue, numericX: numericX ?? index, yValue, definition, radius: numericValue(definition.radius ? chartValue(datum, definition.radius, index) : 4) ?? 4 };
    }).filter((item): item is NonNullable<typeof item> => item != null));
    const raw = stackChartValues(unstacked.map((item) => ({ ...item, stack: item.definition.stack, x: item.xValue, value: item.yValue })));
    const fullX = this.xDomain ?? chartDomain(raw.map((item) => item.numericX)) ?? [0, 1];
    const fullY = this.yDomain ?? chartDomain(raw.flatMap((item) => [item.start, item.end]), { includeZero: active.some((item) => item.type === 'bar' || this.kind === 'bar') }) ?? [0, 1];
    const xDomain = this.effectiveViewport.x ?? fullX;
    const yDomain = this.effectiveViewport.y ?? fullY;
    const bands = this.xScale === 'band' ? bandScale(raw.map((item) => item.xValue), [layout.left, layout.left + layout.plotWidth]) : null;
    const xMap = (this.xScale === 'log' ? logScale : linearScale)(xDomain, [layout.left, layout.left + layout.plotWidth]);
    const yMap = (this.yScale === 'log' ? logScale : linearScale)(yDomain, [layout.top + layout.plotHeight, layout.top]);
    const marks: Mark[] = [];
    const canvasMarks: CanvasMark[] = [];
    const points: { id: string; label: string; yValue: number }[] = [];
    for (const [seriesIndex, definition] of active.entries()) {
      const type = definition.type ?? (this.kind === 'combo' ? 'line' : this.kind);
      const color = definition.color ?? colors[seriesIndex % colors.length]!;
      const values = raw.filter((item) => item.definition === definition).map((item) => ({ ...item, x: bands ? bands.map(item.xValue) + bands.bandwidth / 2 : xMap(item.numericX), y: yMap(item.end), y0: yMap(item.start) }));
      points.push(...values.map((item) => ({ id: definition.id, label: definition.label ?? definition.id, yValue: item.yValue })));
      if (type === 'line' || type === 'area') {
        const path = type === 'line' ? linePath(values.map((item) => [item.x, item.y])) : definition.stack ? stackedAreaPath(values.map((item) => ({ x: item.x, y0: item.y0, y1: item.y }))) : areaPath(values.map((item) => [item.x, item.y]), yMap(0));
        marks.push({ id: definition.id, type, color, path });
        canvasMarks.push(type === 'line' ? { type: 'line', points: values.map((item) => [item.x, item.y]), color } : { type: 'area', points: values.map((item) => [item.x, item.y]), baseline: yMap(0), color, opacity: 0.3 });
      } else for (const item of values) {
        if (type === 'bar' || type === 'heatmap') {
          const width = type === 'bar' ? bands?.bandwidth ?? 8 : 10;
          const origin = definition.stack ? item.y0 : yMap(0);
          const y = type === 'bar' ? Math.min(item.y, origin) : item.y - 5;
          const height = type === 'bar' ? Math.abs(item.y - origin) : 10;
          marks.push({ id: definition.id, type, color, x: item.x - width / 2, y, width, height });
          canvasMarks.push({ type: 'rect', x: item.x - width / 2, y, width, height, color });
        } else {
          const radius = type === 'bubble' ? item.radius : 3;
          marks.push({ id: definition.id, type, color, x: item.x, y: item.y, radius });
          canvasMarks.push({ type: 'point', x: item.x, y: item.y, radius, color });
        }
      }
    }
    const useCanvas = this.renderMode === 'canvas' || (this.renderMode === 'auto' && points.length > this.canvasThreshold);
    const current = points[Math.min(this.focused, points.length - 1)];
    return { marks, canvasMarks, useCanvas, xDomain: fullX, yDomain: fullY, summary: chartSummary(points.map((item) => item.yValue)), tooltip: current ? `${current.label}: ${current.yValue}` : '', legend: definitions.map((item, index) => ({ id: item.id, label: item.label ?? item.id, color: item.color ?? colors[index % colors.length] })) };
  }

  ngAfterViewChecked(): void {
    const model = this.model;
    const signature = `${this.rows.length}:${model.marks.length}:${this.width}:${this.height}`;
    if (!model.useCanvas || !this.canvas || signature === this.drawn) return;
    this.drawn = signature;
    void import('@simurgh-ui/core/chart-canvas').then(({ drawChartCanvas }) => {
      const context = this.canvas?.nativeElement.getContext('2d');
      if (context) drawChartCanvas(context, model.canvasMarks, this.width, this.height, globalThis.devicePixelRatio || 1);
    });
  }

  onKeydown(event: KeyboardEvent) {
    const size = this.model.marks.length;
    if (event.key === 'Home') this.focused = 0;
    else if (event.key === 'End') this.focused = Math.max(0, size - 1);
    else if (['ArrowLeft', 'ArrowUp'].includes(event.key)) this.focused = Math.max(0, this.focused - 1);
    else if (['ArrowRight', 'ArrowDown'].includes(event.key)) this.focused = Math.min(Math.max(0, size - 1), this.focused + 1);
    else return;
    event.preventDefault();
  }
  onWheel(event: WheelEvent) {
    if (!this.interaction || (!this.axisEnabled(this.interaction.zoom, 'x') && !this.axisEnabled(this.interaction.zoom, 'y'))) return;
    event.preventDefault();
    const bounds = (event.currentTarget as HTMLElement).getBoundingClientRect();
    const point: readonly [number, number] = [((event.clientX - bounds.left) / bounds.width) * this.width, ((event.clientY - bounds.top) / bounds.height) * this.height];
    const layout = chartLayout(this.width, this.height);
    const model = this.model;
    const fullX = 'xDomain' in model ? model.xDomain : [0, 1] as ChartDomain;
    const fullY = 'yDomain' in model ? model.yDomain : [0, 1] as ChartDomain;
    const next = { ...this.effectiveViewport };
    const factor = event.deltaY < 0 ? 1.2 : 1 / 1.2;
    if (this.axisEnabled(this.interaction.zoom, 'x')) next.x = clampDomain(zoomDomain(this.effectiveViewport.x ?? fullX, factor, domainFromSelection(this.effectiveViewport.x ?? fullX, [point[0], point[0]], [layout.left, layout.left + layout.plotWidth])[0]), fullX);
    if (this.axisEnabled(this.interaction.zoom, 'y')) next.y = clampDomain(zoomDomain(this.effectiveViewport.y ?? fullY, factor, domainFromSelection(this.effectiveViewport.y ?? fullY, [point[1], point[1]], [layout.top + layout.plotHeight, layout.top])[0]), fullY);
    if (this.viewport === undefined) this.uncontrolledViewport = next;
    this.viewportChange.emit(next);
    this.changeDetector?.markForCheck();
  }
  private axisEnabled(value: boolean | 'x' | 'y' | 'xy' | undefined, axis: 'x' | 'y') { return value === true || value === 'xy' || value === axis; }
  toggleSeries(id: string) {
    const hidden = this.effectiveHiddenSeries;
    const next = hidden.includes(id) ? hidden.filter((item) => item !== id) : [...hidden, id];
    if (this.hiddenSeries === undefined) this.uncontrolledHiddenSeries = next;
    this.hiddenSeriesChange.emit(next);
  }
  ngOnDestroy(): void { this.unsubscribeStream?.(); }
  private polarModel() {
    const value = this.y ?? this.series?.[0]?.y;
    const radius = Math.min(this.width, this.height) / 2 - 16;
    const arcs = value ? pieArcs(this.rows, value, radius, this.kind === 'donut' ? this.innerRadius ?? radius * 0.55 : this.innerRadius ?? 0) : [];
    return { marks: arcs.map((arc, index): Mark => ({ id: String(arc.index), type: 'area', color: colors[index % colors.length]!, path: arc.path })), canvasMarks: [], useCanvas: false, xDomain: [0, 1] as ChartDomain, yDomain: [0, 1] as ChartDomain, summary: chartSummary(arcs.map((arc) => arc.value), 'Slices'), tooltip: '', legend: [] };
  }
}

function chartMetadata(selector: string) {
  return Component({ selector, standalone: true, imports: [CommonModule], template, host: { class: 'simurgh-chart', 'data-slot': 'chart', '[attr.data-state]': "model.marks.length ? null : 'empty'", '[attr.aria-hidden]': 'decorative || null' } });
}

@chartMetadata('simurgh-line-chart') export class LineChartComponent extends ChartBaseComponent { readonly kind = 'line'; }
@chartMetadata('simurgh-area-chart') export class AreaChartComponent extends ChartBaseComponent { readonly kind = 'area'; }
@chartMetadata('simurgh-bar-chart') export class BarChartComponent extends ChartBaseComponent { readonly kind = 'bar'; override xScale: 'linear' | 'time' | 'band' | 'log' = 'band'; }
@chartMetadata('simurgh-scatter-chart') export class ScatterChartComponent extends ChartBaseComponent { readonly kind = 'scatter'; }
@chartMetadata('simurgh-bubble-chart') export class BubbleChartComponent extends ChartBaseComponent { readonly kind = 'bubble'; }
@chartMetadata('simurgh-heatmap-chart') export class HeatmapChartComponent extends ChartBaseComponent { readonly kind = 'heatmap'; }
@chartMetadata('simurgh-combo-chart') export class ComboChartComponent extends ChartBaseComponent { readonly kind = 'combo'; }
@chartMetadata('simurgh-pie-chart') export class PieChartComponent extends ChartBaseComponent { readonly kind = 'pie'; }
@chartMetadata('simurgh-donut-chart') export class DonutChartComponent extends ChartBaseComponent { readonly kind = 'donut'; }

@Component({ selector: 'simurgh-radar-chart', standalone: true, template: `<svg [attr.viewBox]="viewBox" data-part="plot" aria-hidden="true"><polygon data-part="series" [attr.points]="points" fill="hsl(var(--simurgh-chart-1))" stroke="hsl(var(--simurgh-chart-1))"></polygon></svg><figcaption *ngIf="!decorative">{{ accessibility.title }}</figcaption><p *ngIf="!decorative" data-part="description">{{ accessibility.description }} {{ summary }}</p>`, imports: [CommonModule], host: { class: 'simurgh-chart', 'data-slot': 'chart' } })
export class RadarChartComponent {
  @Input() data: readonly Datum[] = [];
  @Input() stream?: ChartStream<string>;
  @Input({ required: true }) y!: ChartAccessor<Datum, number>;
  @Input({ required: true }) accessibility!: ChartAccessibility;
  @Input() width = 360;
  @Input() height = 360;
  get rows(): readonly Datum[] { if (!this.stream) return this.data; const snapshot = this.stream.snapshot(); const step = Math.max(1, Math.ceil(snapshot.length / Math.max(2, this.width * 2))); return Array.from({ length: Math.ceil(snapshot.length / step) }, (_, index) => Object.fromEntries(this.stream!.dimensions.map((key) => [key, snapshot.columns[key]![index * step]])) as Datum); }
  get values() { return this.rows.map((datum, index) => numericValue(chartValue(datum, this.y, index))).filter((item): item is number => item != null); }
  get points() { return radarPoints(this.values, Math.min(this.width, this.height) / 2 - 24); }
  get viewBox() { return `${-this.width / 2} ${-this.height / 2} ${this.width} ${this.height}`; }
  get decorative() { return 'decorative' in this.accessibility && this.accessibility.decorative; }
  get summary() { return chartSummary(this.values); }
}

@Component({ selector: 'simurgh-chart-root', standalone: true, template: '<ng-content />', host: { class: 'simurgh-chart', 'data-slot': 'chart' } }) export class ChartRootComponent {}
@Component({ selector: 'simurgh-chart-plot', standalone: true, template: '<svg data-part="plot"><ng-content /></svg>' }) export class ChartPlotComponent {}
@Directive({ selector: '[simurghChartGrid]', standalone: true, host: { 'data-part': 'grid' } }) export class ChartGridDirective {}
@Directive({ selector: '[simurghChartXAxis]', standalone: true, host: { 'data-part': 'x-axis' } }) export class ChartXAxisDirective {}
@Directive({ selector: '[simurghChartYAxis]', standalone: true, host: { 'data-part': 'y-axis' } }) export class ChartYAxisDirective {}
@Directive({ selector: '[simurghChartLegend]', standalone: true, host: { 'data-part': 'legend' } }) export class ChartLegendDirective {}
@Directive({ selector: '[simurghChartTooltip]', standalone: true, host: { 'data-part': 'tooltip', role: 'tooltip' } }) export class ChartTooltipDirective {}
@Directive({ selector: '[simurghChartCrosshair]', standalone: true, host: { 'data-part': 'crosshair' } }) export class ChartCrosshairDirective {}
@Directive({ selector: '[simurghChartBrush]', standalone: true, host: { 'data-part': 'brush' } }) export class ChartBrushDirective {}
