// packages/react/src/components/disclosure.tsx
import { useOpen, type OpenProps } from '../internal/open.js';
import React, { forwardRef, type HTMLAttributes } from 'react';

export const Disclosure = forwardRef<
  HTMLDetailsElement,
  React.DetailsHTMLAttributes<HTMLDetailsElement> & OpenProps
>(function Disclosure(
  { open: controlled, defaultOpen, onOpenChange, onToggle, ...props },
  ref,
) {
  const stateOptions: OpenProps = {};
  if (controlled !== undefined) stateOptions.open = controlled;
  if (defaultOpen !== undefined) stateOptions.defaultOpen = defaultOpen;
  if (onOpenChange) stateOptions.onOpenChange = onOpenChange;
  const [open, setOpen] = useOpen(stateOptions);
  return (
    <details
      ref={ref}
      {...props}
      open={open}
      data-slot="disclosure"
      data-state={open ? 'open' : 'closed'}
      onToggle={(event) => {
        setOpen(event.currentTarget.open);
        onToggle?.(event);
      }}
    />
  );
});
export const DisclosureSummary = forwardRef<
  HTMLElement,
  HTMLAttributes<HTMLElement>
>(function DisclosureSummary(props, ref) {
  return <summary ref={ref} data-slot="disclosure-summary" {...props} />;
});
export const DisclosureContent = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function DisclosureContent(props, ref) {
  return <div ref={ref} data-slot="disclosure-content" {...props} />;
});

// packages/angular/src/components/disclosure.ts
import {
  Component,
  Directive,
  EventEmitter,
  Input,
  Output,
} from '@angular/core';

@Component({
  selector: 'simurgh-disclosure',
  standalone: true,
  template: `<details
    data-slot="disclosure"
    [open]="open"
    [attr.data-state]="open ? 'open' : 'closed'"
    (toggle)="onToggle($event)"
  >
    <ng-content />
  </details>`,
})
export class DisclosureComponent {
  @Input() open = false;
  @Output() openChange = new EventEmitter<boolean>();

  onToggle(event: Event) {
    const next = (event.currentTarget as HTMLDetailsElement).open;
    if (next === this.open) return;
    this.open = next;
    this.openChange.emit(next);
  }
}

@Directive({
  selector: 'summary[simurghDisclosureSummary]',
  standalone: true,
  host: { 'data-slot': 'disclosure-summary' },
})
export class DisclosureSummaryDirective {}

@Directive({
  selector: '[simurghDisclosureContent]',
  standalone: true,
  host: { 'data-slot': 'disclosure-content' },
})
export class DisclosureContentDirective {}
