// packages/cli/assets/lit/disclosure.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-disclosure')
export class Disclosure extends LitElement {
  @property({ type: Boolean, reflect: true }) open = false;
  render() {
    return html`<details
      part="root"
      .open=${this.open}
      data-slot="disclosure"
      data-state=${this.open ? 'open' : 'closed'}
      @toggle=${(e: Event) => (this.open = (e.target as HTMLDetailsElement).open)}
    >
      <summary part="summary" data-slot="disclosure-summary">
        <slot name="summary"></slot>
      </summary>
      <div part="content" data-slot="disclosure-content"><slot></slot></div>
    </details>`;
  }
}

// packages/angular/src/components/disclosure.ts
import {
  Component,
  Directive,
  EventEmitter,
  Input,
  Output,
} from '@angular/core';

@Component({
  selector: 'simurgh-disclosure',
  standalone: true,
  template: `<details
    data-slot="disclosure"
    [open]="open"
    [attr.data-state]="open ? 'open' : 'closed'"
    (toggle)="onToggle($event)"
  >
    <ng-content />
  </details>`,
})
export class DisclosureComponent {
  @Input() open = false;
  @Output() openChange = new EventEmitter<boolean>();

  onToggle(event: Event) {
    const next = (event.currentTarget as HTMLDetailsElement).open;
    if (next === this.open) return;
    this.open = next;
    this.openChange.emit(next);
  }
}

@Directive({
  selector: 'summary[simurghDisclosureSummary]',
  standalone: true,
  host: { 'data-slot': 'disclosure-summary' },
})
export class DisclosureSummaryDirective {}

@Directive({
  selector: '[simurghDisclosureContent]',
  standalone: true,
  host: { 'data-slot': 'disclosure-content' },
})
export class DisclosureContentDirective {}
