// packages/react/src/components/input-group.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export const InputGroup = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function InputGroup({ role = 'group', ...props }, ref) {
  return <div ref={ref} role={role} data-slot="input-group" {...props} />;
});

export const InputGroupAddon = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement> & {
    align?: 'inline-start' | 'inline-end' | 'block-start' | 'block-end';
    decorative?: boolean;
  }
>(function InputGroupAddon(
  { align = 'inline-start', decorative = false, ...props },
  ref,
) {
  return (
    <div
      ref={ref}
      aria-hidden={decorative || undefined}
      data-align={align}
      data-slot="input-group-addon"
      {...props}
    />
  );
});

export const InputGroupText = /* @__PURE__ */ forwardRef<
  HTMLSpanElement,
  HTMLAttributes<HTMLSpanElement>
>(function InputGroupText(props, ref) {
  return <span ref={ref} data-slot="input-group-text" {...props} />;
});

// packages/angular/src/components/input-group.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'simurgh-input-group',
  standalone: true,
  template: `<ng-content />`,
  host: { role: 'group', '[attr.data-slot]': "'input-group'" },
})
export class InputGroupComponent {}

@Component({
  selector: 'simurgh-input-group-addon',
  standalone: true,
  template: `<ng-content />`,
  host: {
    '[attr.aria-hidden]': 'decorative || null',
    '[attr.data-align]': 'align',
    '[attr.data-slot]': "'input-group-addon'",
  },
})
export class InputGroupAddonComponent {
  @Input() align: 'inline-start' | 'inline-end' | 'block-start' | 'block-end' =
    'inline-start';
  @Input() decorative = false;
}

@Component({
  selector: 'simurgh-input-group-text',
  standalone: true,
  template: `<ng-content />`,
  host: { '[attr.data-slot]': "'input-group-text'" },
})
export class InputGroupTextComponent {}
