// packages/react/src/components/input-otp.tsx
import {
  forwardRef,
  type CSSProperties,
  type InputHTMLAttributes,
} from 'react';

export const InputOtp = /* @__PURE__ */ forwardRef<
  HTMLInputElement,
  Omit<InputHTMLAttributes<HTMLInputElement>, 'maxLength'> & {
    length?: number;
    digitsOnly?: boolean;
    invalid?: boolean;
  }
>(function InputOtp(
  {
    length = 6,
    digitsOnly = true,
    invalid = false,
    autoComplete = 'one-time-code',
    inputMode,
    pattern,
    style,
    onInput,
    ...props
  },
  ref,
) {
  return (
    <input
      ref={ref}
      type="text"
      maxLength={length}
      autoComplete={autoComplete}
      inputMode={inputMode ?? (digitsOnly ? 'numeric' : 'text')}
      pattern={pattern ?? (digitsOnly ? '[0-9]*' : undefined)}
      aria-invalid={invalid || undefined}
      data-slot="input-otp"
      style={{ '--simurgh-otp-length': length, ...style } as CSSProperties}
      onInput={(event) => {
        if (digitsOnly) {
          event.currentTarget.value = event.currentTarget.value
            .replace(/\D/g, '')
            .slice(0, length);
        }
        onInput?.(event);
      }}
      {...props}
    />
  );
});

// packages/angular/src/components/input-otp.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'simurgh-input-otp',
  standalone: true,
  template: `<input
    type="text"
    data-slot="input-otp"
    [name]="name || ''"
    [value]="value"
    [maxLength]="length"
    [required]="required"
    [disabled]="disabled"
    [attr.autocomplete]="autocomplete"
    [attr.inputmode]="digitsOnly ? 'numeric' : 'text'"
    [attr.pattern]="digitsOnly ? '[0-9]*' : null"
    [attr.aria-invalid]="invalid || null"
    [style.--simurgh-otp-length]="length"
    (input)="update($event)"
  />`,
})
export class InputOtpComponent {
  @Input() name?: string;
  @Input() value = '';
  @Input() length = 6;
  @Input() digitsOnly = true;
  @Input() required = false;
  @Input() disabled = false;
  @Input() invalid = false;
  @Input() autocomplete = 'one-time-code';
  @Output() valueChange = new EventEmitter<string>();
  update(event: Event) {
    const input = event.target as HTMLInputElement;
    this.value = (
      this.digitsOnly ? input.value.replace(/\D/g, '') : input.value
    ).slice(0, this.length);
    input.value = this.value;
    this.valueChange.emit(this.value);
  }
}
