// packages/react/src/components/item.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export const ItemGroup = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function ItemGroup({ role = 'list', ...props }, ref) {
  return <div ref={ref} role={role} data-slot="item-group" {...props} />;
});

export const Item = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function Item({ role = 'listitem', ...props }, ref) {
  return <div ref={ref} role={role} data-slot="item" {...props} />;
});

export const ItemMedia = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement> & { decorative?: boolean }
>(function ItemMedia({ decorative = true, ...props }, ref) {
  return (
    <div
      ref={ref}
      aria-hidden={decorative || undefined}
      data-slot="item-media"
      {...props}
    />
  );
});

export const ItemContent = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function ItemContent(props, ref) {
  return <div ref={ref} data-slot="item-content" {...props} />;
});

export const ItemTitle = /* @__PURE__ */ forwardRef<
  HTMLHeadingElement,
  HTMLAttributes<HTMLHeadingElement>
>(function ItemTitle(props, ref) {
  return <h3 ref={ref} data-slot="item-title" {...props} />;
});

export const ItemDescription = /* @__PURE__ */ forwardRef<
  HTMLParagraphElement,
  HTMLAttributes<HTMLParagraphElement>
>(function ItemDescription(props, ref) {
  return <p ref={ref} data-slot="item-description" {...props} />;
});

export const ItemActions = /* @__PURE__ */ forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function ItemActions(props, ref) {
  return <div ref={ref} data-slot="item-actions" {...props} />;
});

// packages/angular/src/components/item.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'simurgh-item-group',
  standalone: true,
  template: `<ng-content />`,
  host: { role: 'list', '[attr.data-slot]': "'item-group'" },
})
export class ItemGroupComponent {}

@Component({
  selector: 'simurgh-item',
  standalone: true,
  template: `<ng-content />`,
  host: { role: 'listitem', '[attr.data-slot]': "'item'" },
})
export class ItemComponent {}

@Component({
  selector: 'simurgh-item-media',
  standalone: true,
  template: `<ng-content />`,
  host: {
    '[attr.aria-hidden]': 'decorative || null',
    '[attr.data-slot]': "'item-media'",
  },
})
export class ItemMediaComponent {
  @Input() decorative = true;
}

@Component({
  selector: 'simurgh-item-content',
  standalone: true,
  template: `<ng-content />`,
  host: { '[attr.data-slot]': "'item-content'" },
})
export class ItemContentComponent {}

@Component({
  selector: 'simurgh-item-title',
  standalone: true,
  template: `<h3 data-slot="item-title"><ng-content /></h3>`,
})
export class ItemTitleComponent {}

@Component({
  selector: 'simurgh-item-description',
  standalone: true,
  template: `<p data-slot="item-description"><ng-content /></p>`,
})
export class ItemDescriptionComponent {}

@Component({
  selector: 'simurgh-item-actions',
  standalone: true,
  template: `<ng-content />`,
  host: { '[attr.data-slot]': "'item-actions'" },
})
export class ItemActionsComponent {}
