// packages/react/src/components/pagination.tsx
import {
  forwardRef,
  type AnchorHTMLAttributes,
  type HTMLAttributes,
  type LiHTMLAttributes,
} from 'react';

export const Pagination = /* @__PURE__ */ forwardRef<
  HTMLElement,
  HTMLAttributes<HTMLElement> & { label?: string }
>(function Pagination({ label = 'Pagination', ...props }, ref) {
  return <nav ref={ref} aria-label={label} data-slot="pagination" {...props} />;
});
export const PaginationContent = /* @__PURE__ */ forwardRef<
  HTMLUListElement,
  HTMLAttributes<HTMLUListElement>
>(function PaginationContent(props, ref) {
  return <ul ref={ref} data-slot="pagination-content" {...props} />;
});
export const PaginationItem = /* @__PURE__ */ forwardRef<
  HTMLLIElement,
  LiHTMLAttributes<HTMLLIElement>
>(function PaginationItem(props, ref) {
  return <li ref={ref} data-slot="pagination-item" {...props} />;
});
export const PaginationLink = /* @__PURE__ */ forwardRef<
  HTMLAnchorElement,
  AnchorHTMLAttributes<HTMLAnchorElement> & { current?: boolean }
>(function PaginationLink({ current = false, ...props }, ref) {
  return (
    <a
      ref={ref}
      aria-current={current ? 'page' : undefined}
      data-slot="pagination-link"
      {...props}
    />
  );
});

// packages/angular/src/components/pagination.ts
import { Component, Directive, Input } from '@angular/core';

@Component({
  selector: 'simurgh-pagination',
  standalone: true,
  template: `<nav [attr.aria-label]="label" data-slot="pagination">
    <ng-content />
  </nav>`,
})
export class PaginationComponent {
  @Input() label = 'Pagination';
}

@Directive({
  selector: 'ul[simurghPaginationContent]',
  standalone: true,
  host: { 'data-slot': 'pagination-content' },
})
export class PaginationContentDirective {}

@Directive({
  selector: 'li[simurghPaginationItem]',
  standalone: true,
  host: { 'data-slot': 'pagination-item' },
})
export class PaginationItemDirective {}

@Directive({
  selector: 'a[simurghPaginationLink]',
  standalone: true,
  host: {
    'data-slot': 'pagination-link',
    '[attr.aria-current]': "current ? 'page' : null",
  },
})
export class PaginationLinkDirective {
  @Input() current = false;
}
