// packages/react/src/components/password-input.tsx
import { forwardRef, useId, useState, type InputHTMLAttributes } from 'react';

type PasswordInputProps = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type'
> & {
  revealLabel?: string;
  concealLabel?: string;
};
export const PasswordInput = /* @__PURE__ */ forwardRef<
  HTMLInputElement,
  PasswordInputProps
>(function PasswordInput(
  {
    revealLabel = 'Show password',
    concealLabel = 'Hide password',
    disabled,
    ...props
  },
  ref,
) {
  const [revealed, setRevealed] = useState(false);
  const id = props.id ?? `simurgh-password-${useId().replace(/:/g, '')}`;
  return (
    <div data-slot="password-input" data-disabled={disabled || undefined}>
      <input
        {...props}
        ref={ref}
        id={id}
        type={revealed ? 'text' : 'password'}
        data-slot="password-input-control"
        disabled={disabled}
      />
      <button
        type="button"
        data-slot="password-input-toggle"
        aria-controls={id}
        aria-label={revealed ? concealLabel : revealLabel}
        aria-pressed={revealed}
        disabled={disabled}
        onClick={() => setRevealed((current) => !current)}
      >
        {revealed ? 'Hide' : 'Show'}
      </button>
    </div>
  );
});

// packages/angular/src/components/password-input.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { createId } from '@simurgh-ui/core';

@Component({
  selector: 'simurgh-password-input',
  standalone: true,
  template: `<div
    data-slot="password-input"
    [attr.data-disabled]="disabled || null"
  >
    <input
      [id]="inputId"
      [type]="revealed ? 'text' : 'password'"
      data-slot="password-input-control"
      [attr.aria-label]="ariaLabel"
      [attr.name]="name || null"
      [attr.autocomplete]="autocomplete || null"
      [attr.placeholder]="placeholder || null"
      [value]="value"
      [disabled]="disabled"
      [readOnly]="readonly"
      [required]="required"
      (input)="onInput($event)"
    />
    <button
      type="button"
      data-slot="password-input-toggle"
      [attr.aria-controls]="inputId"
      [attr.aria-label]="revealed ? concealLabel : revealLabel"
      [attr.aria-pressed]="revealed"
      [disabled]="disabled"
      (click)="revealed = !revealed"
    >
      {{ revealed ? 'Hide' : 'Show' }}
    </button>
  </div>`,
})
export class PasswordInputComponent {
  @Input() inputId = createId('password');
  @Input('aria-label') ariaLabel = 'Password';
  @Input() value = '';
  @Input() name?: string;
  @Input() autocomplete = 'current-password';
  @Input() placeholder?: string;
  @Input() disabled = false;
  @Input() readonly = false;
  @Input() required = false;
  @Input() revealLabel = 'Show password';
  @Input() concealLabel = 'Hide password';
  @Output() valueChange = new EventEmitter<string>();
  revealed = false;
  onInput(event: Event) {
    this.value = (event.currentTarget as HTMLInputElement).value;
    this.valueChange.emit(this.value);
  }
}
