// packages/react/src/components/specialty-charts.tsx
import { specialtyChartMarks, specialtyChartSummary, type SpecialtyChartKind, type SpecialtyDatum, type SpecialtyMark } from '@simurgh-ui/core/specialty-charts';
import type { ChartAccessibility } from '@simurgh-ui/core/charts';
import type { HTMLAttributes } from 'react';

export type SpecialtyChartProps = Omit<HTMLAttributes<HTMLElement>, 'title'> & { data: readonly SpecialtyDatum[]; accessibility: ChartAccessibility; width?: number; height?: number };

function Mark({ mark, index }: { mark: SpecialtyMark; index: number }) {
  const color = `hsl(var(--simurgh-chart-${index % 10 + 1}))`;
  if (mark.type === 'path') return <path data-part={mark.part} d={mark.path} fill={mark.part === 'link' ? 'none' : color} stroke={color} strokeWidth={mark.part === 'link' ? Math.max(2, Math.sqrt(Math.abs(mark.value))) : 1} />;
  if (mark.type === 'rect') return <rect data-part={mark.part} x={mark.x} y={mark.y} width={mark.width} height={mark.height} fill={color} stroke="currentColor" />;
  if (mark.type === 'line') return <line data-part={mark.part} x1={mark.x} y1={mark.y} x2={mark.x2} y2={mark.y2} stroke={color} strokeWidth="2" />;
  if (mark.type === 'circle') return <circle data-part={mark.part} cx={mark.x} cy={mark.y} r={mark.radius} fill={color} />;
  return <text data-part={mark.part} x={mark.x} y={mark.y}>{mark.label}</text>;
}

export function SpecialtyChart({ kind, data, accessibility, width = 640, height = 360, ...native }: SpecialtyChartProps & { kind: SpecialtyChartKind }) {
  const marks = specialtyChartMarks(kind, data, width, height);
  const decorative = 'decorative' in accessibility && accessibility.decorative;
  return <figure className="simurgh-chart" data-slot="chart" data-kind={kind} data-state={marks.length ? undefined : 'empty'} aria-hidden={decorative || undefined} {...native}>
    {!decorative && <figcaption>{accessibility.title}</figcaption>}
    <svg viewBox={`0 0 ${width} ${height}`} data-part="plot" aria-hidden="true">{marks.map((item, index) => <Mark key={`${item.part}:${item.label}:${index}`} mark={item} index={index} />)}</svg>
    {!decorative && <><p data-part="description">{accessibility.description} {specialtyChartSummary(kind, marks)}</p><ul data-part="data-list" className="simurgh-visually-hidden">{marks.filter((item, index, all) => all.findIndex((candidate) => candidate.label === item.label) === index).map((item) => <li key={item.label}>{item.label}: {item.value}</li>)}</ul></>}
  </figure>;
}

const chart = (kind: SpecialtyChartKind) => (props: SpecialtyChartProps) => <SpecialtyChart {...props} kind={kind} />;
export const CandlestickChart = chart('candlestick');
export const OhlcChart = chart('ohlc');
export const BoxPlotChart = chart('box-plot');
export const ViolinChart = chart('violin');
export const HistogramChart = chart('histogram');
export const FunnelChart = chart('funnel');
export const GaugeChart = chart('gauge');
export const PolarAreaChart = chart('polar-area');
export const WaterfallChart = chart('waterfall');
export const TreemapChart = chart('treemap');
export const SankeyChart = chart('sankey');
export const GeoChart = chart('geo');
export const MapChart = GeoChart;

// packages/angular/src/components/specialty-charts.ts
import { CommonModule } from '@angular/common';
import { Component, Directive, Input } from '@angular/core';
import type { ChartAccessibility } from '@simurgh-ui/core/charts';
import { specialtyChartMarks, specialtyChartSummary, type SpecialtyChartKind, type SpecialtyDatum } from '@simurgh-ui/core/specialty-charts';

const template = `<figcaption *ngIf="!decorative">{{ accessibility.title }}</figcaption><svg [attr.viewBox]="'0 0 ' + width + ' ' + height" data-part="plot" aria-hidden="true"><ng-container *ngFor="let mark of marks; let index = index"><path *ngIf="mark.type === 'path'" [attr.data-part]="mark.part" [attr.d]="mark.path" [attr.fill]="mark.part === 'link' ? 'none' : color(index)" [attr.stroke]="color(index)" [attr.stroke-width]="mark.part === 'link' ? linkWidth(mark.value) : 1"></path><rect *ngIf="mark.type === 'rect'" [attr.data-part]="mark.part" [attr.x]="mark.x" [attr.y]="mark.y" [attr.width]="mark.width" [attr.height]="mark.height" [attr.fill]="color(index)" stroke="currentColor"></rect><line *ngIf="mark.type === 'line'" [attr.data-part]="mark.part" [attr.x1]="mark.x" [attr.y1]="mark.y" [attr.x2]="mark.x2" [attr.y2]="mark.y2" [attr.stroke]="color(index)" stroke-width="2"></line><circle *ngIf="mark.type === 'circle'" [attr.data-part]="mark.part" [attr.cx]="mark.x" [attr.cy]="mark.y" [attr.r]="mark.radius" [attr.fill]="color(index)"></circle></ng-container></svg><ng-container *ngIf="!decorative"><p data-part="description">{{ accessibility.description }} {{ summary }}</p><ul data-part="data-list" class="simurgh-visually-hidden"><li *ngFor="let item of uniqueMarks">{{ item.label }}: {{ item.value }}</li></ul></ng-container>`;
@Directive()
export abstract class SpecialtyChartComponent {
  @Input({ required: true }) data: readonly SpecialtyDatum[] = [];
  @Input({ required: true }) accessibility!: ChartAccessibility;
  @Input() width = 640; @Input() height = 360;
  abstract readonly kind: SpecialtyChartKind;
  get decorative() { return 'decorative' in this.accessibility && this.accessibility.decorative; }
  get marks() { return specialtyChartMarks(this.kind, this.data, this.width, this.height); }
  get uniqueMarks() { return this.marks.filter((item, index, all) => all.findIndex((candidate) => candidate.label === item.label) === index); }
  get summary() { return specialtyChartSummary(this.kind, this.marks); }
  color(index: number) { return `hsl(var(--simurgh-chart-${index % 10 + 1}))`; }
  linkWidth(value: number) { return Math.max(2, Math.sqrt(Math.abs(value))); }
}
const metadata = (selector: string) => Component({ selector, standalone: true, imports: [CommonModule], template, host: { class: 'simurgh-chart', 'data-slot': 'chart', '[attr.data-kind]': 'kind', '[attr.aria-hidden]': 'decorative || null' } });
@metadata('simurgh-candlestick-chart') export class CandlestickChartComponent extends SpecialtyChartComponent { readonly kind = 'candlestick'; }
@metadata('simurgh-ohlc-chart') export class OhlcChartComponent extends SpecialtyChartComponent { readonly kind = 'ohlc'; }
@metadata('simurgh-box-plot-chart') export class BoxPlotChartComponent extends SpecialtyChartComponent { readonly kind = 'box-plot'; }
@metadata('simurgh-violin-chart') export class ViolinChartComponent extends SpecialtyChartComponent { readonly kind = 'violin'; }
@metadata('simurgh-histogram-chart') export class HistogramChartComponent extends SpecialtyChartComponent { readonly kind = 'histogram'; }
@metadata('simurgh-funnel-chart') export class FunnelChartComponent extends SpecialtyChartComponent { readonly kind = 'funnel'; }
@metadata('simurgh-gauge-chart') export class GaugeChartComponent extends SpecialtyChartComponent { readonly kind = 'gauge'; }
@metadata('simurgh-polar-area-chart') export class PolarAreaChartComponent extends SpecialtyChartComponent { readonly kind = 'polar-area'; }
@metadata('simurgh-waterfall-chart') export class WaterfallChartComponent extends SpecialtyChartComponent { readonly kind = 'waterfall'; }
@metadata('simurgh-treemap-chart') export class TreemapChartComponent extends SpecialtyChartComponent { readonly kind = 'treemap'; }
@metadata('simurgh-sankey-chart') export class SankeyChartComponent extends SpecialtyChartComponent { readonly kind = 'sankey'; }
@metadata('simurgh-geo-chart') export class GeoChartComponent extends SpecialtyChartComponent { readonly kind = 'geo'; }
@metadata('simurgh-map-chart') export class MapChartComponent extends SpecialtyChartComponent { readonly kind = 'geo'; }
