// packages/lit/src/components/textarea.ts
import { html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { FormControlElement } from '../internal/form-control.js';

@customElement('simurgh-textarea')
export class Textarea extends FormControlElement {
  @property() value = '';
  @property() placeholder = '';
  @property({ type: Boolean }) invalid = false;
  private initialValue = '';
  connectedCallback() {
    super.connectedCallback();
    this.initialValue = this.value;
    this.updateFormValue(this.value);
  }
  formResetCallback() {
    this.value = this.initialValue;
    this.updateFormValue(this.value);
  }
  private onInput(event: Event) {
    this.value = (event.currentTarget as HTMLTextAreaElement).value;
    this.updateFormValue(this.value);
  }
  render() {
    return html`<textarea
      part="control"
      .value=${this.value}
      placeholder=${this.placeholder}
      ?disabled=${this.disabled}
      ?required=${this.required}
      aria-invalid=${this.invalid ? 'true' : 'false'}
      @input=${this.onInput}
    ></textarea>`;
  }
}

// packages/angular/src/components/textarea.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormResetBase } from '../internal/form-reset.js';

@Component({
  selector: 'simurgh-textarea',
  standalone: true,
  template: `<textarea
    [name]="name || ''"
    [value]="value"
    [required]="required"
    [disabled]="disabled"
    [attr.aria-invalid]="invalid || null"
    (input)="onInput($event)"
  ></textarea>`,
})
export class TextareaComponent extends FormResetBase {
  @Input() name?: string;
  @Input() value = '';
  @Input() required = false;
  @Input() disabled = false;
  @Input() invalid = false;
  @Output() valueChange = new EventEmitter<string>();
  protected createFormReset() {
    const initial = this.value;
    return () => {
      this.value = initial;
      this.valueChange.emit(initial);
    };
  }
  onInput(event: Event) {
    this.value = (event.target as HTMLTextAreaElement).value;
    this.valueChange.emit(this.value);
  }
}
