// packages/cli/assets/lit/toast.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
export type ToastMessage = {
  id: string;
  title: string;
  description?: string;
  tone?: 'neutral' | 'success' | 'warning' | 'danger';
};
@customElement('simurgh-toast')
export class Toast extends LitElement {
  @property({ attribute: false }) messages: ToastMessage[] = [];
  @property() label = 'Notifications';
  render() {
    return html`<div
      part="viewport"
      aria-label=${this.label}
      data-slot="toast-viewport"
    >
      ${this.messages.map((message) => html`<div part="toast" role=${message.tone === 'danger' ? 'alert' : 'status'} aria-live=${message.tone === 'danger' ? 'assertive' : 'polite'} data-slot="toast" data-tone=${message.tone ?? 'neutral'}><strong>${message.title}</strong>${message.description ? html`<p>${message.description}</p>` : null}<button type="button" aria-label="Dismiss notification" @click=${() => (this.messages = this.messages.filter((item) => item.id !== message.id))}>×</button></div>`)}
    </div>`;
  }
}

// packages/angular/src/components/toast.ts
import { CommonModule } from '@angular/common';
import { Component, signal } from '@angular/core';
import { createId } from '@simurgh-ui/core';

export type ToastMessage = { id: string; title: string; description?: string };

@Component({
  selector: 'simurgh-toast-viewport',
  standalone: true,
  imports: [CommonModule],
  template: `<div
    class="simurgh-toast-region"
    role="region"
    aria-label="Notifications"
  >
    <article
      *ngFor="let item of messages()"
      role="status"
      class="simurgh-content simurgh-toast"
    >
      <strong>{{ item.title }}</strong>
      <p *ngIf="item.description">{{ item.description }}</p>
      <button
        type="button"
        aria-label="Dismiss notification"
        (click)="dismiss(item.id)"
      >
        ×
      </button>
    </article>
  </div>`,
})
export class ToastViewportComponent {
  readonly messages = signal<ToastMessage[]>([]);
  toast(message: Omit<ToastMessage, 'id'>, duration = 5000) {
    const id = createId('toast');
    this.messages.update((items) => [...items, { ...message, id }]);
    if (duration) setTimeout(() => this.dismiss(id), duration);
    return id;
  }
  dismiss(id: string) {
    this.messages.update((items) => items.filter((x) => x.id !== id));
  }
}
