// packages/cli/assets/lit/toggle.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
@customElement('simurgh-toggle')
export class Toggle extends LitElement {
  @property({ type: Boolean, reflect: true }) pressed = false;
  @property({ type: Boolean, reflect: true }) disabled = false;
  render() {
    return html`<button
      part="button"
      type="button"
      aria-pressed=${this.pressed}
      ?disabled=${this.disabled}
      data-slot="toggle"
      data-state=${this.pressed ? 'on' : 'off'}
      @click=${() => {
        if (!this.disabled) this.pressed = !this.pressed;
      }}
    >
      <slot></slot>
    </button>`;
  }
}

// packages/angular/src/components/toggle.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'simurgh-toggle',
  standalone: true,
  template: `<button
    type="button"
    [attr.aria-pressed]="pressed"
    [attr.data-state]="pressed ? 'on' : 'off'"
    [disabled]="disabled"
    (click)="toggle()"
  >
    <ng-content />
  </button>`,
})
export class ToggleComponent {
  @Input() pressed = false;
  @Input() disabled = false;
  @Output() pressedChange = new EventEmitter<boolean>();
  toggle() {
    if (this.disabled) return;
    this.pressed = !this.pressed;
    this.pressedChange.emit(this.pressed);
  }
}
